<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 13 Instrumental variables | Causal Inference in Epidemiology Using R</title>
  <meta name="description" content="An introduction to causal inference with epidemiologic applications in R." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 13 Instrumental variables | Causal Inference in Epidemiology Using R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An introduction to causal inference with epidemiologic applications in R." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 13 Instrumental variables | Causal Inference in Epidemiology Using R" />
  
  <meta name="twitter:description" content="An introduction to causal inference with epidemiologic applications in R." />
  

<meta name="author" content="M. Alan Brookhart" />


<meta name="date" content="2026-08-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="clone-censor-weight.html"/>
<link rel="next" href="sensitivity-analysis.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Causal Inference in Epidemiology Using R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="0.1" data-path="preface.html"><a href="preface.html#who-this-book-is-for"><i class="fa fa-check"></i><b>0.1</b> Who this book is for</a></li>
<li class="chapter" data-level="0.2" data-path="preface.html"><a href="preface.html#how-the-book-works"><i class="fa fa-check"></i><b>0.2</b> How the book works</a></li>
<li class="chapter" data-level="0.3" data-path="preface.html"><a href="preface.html#software"><i class="fa fa-check"></i><b>0.3</b> Software</a></li>
</ul></li>
<li class="part"><span><b>I Foundations</b></span></li>
<li class="chapter" data-level="1" data-path="why.html"><a href="why.html"><i class="fa fa-check"></i><b>1</b> Why causal inference?</a>
<ul>
<li class="chapter" data-level="1.1" data-path="why.html"><a href="why.html#questions-epidemiology-cannot-answer-with-association-alone"><i class="fa fa-check"></i><b>1.1</b> Questions epidemiology cannot answer with association alone</a></li>
<li class="chapter" data-level="1.2" data-path="why.html"><a href="why.html#a-first-look-at-the-data"><i class="fa fa-check"></i><b>1.2</b> A first look at the data</a></li>
<li class="chapter" data-level="1.3" data-path="why.html"><a href="why.html#what-this-book-covers"><i class="fa fa-check"></i><b>1.3</b> What this book covers</a></li>
<li class="chapter" data-level="1.4" data-path="why.html"><a href="why.html#how-to-read-this-book"><i class="fa fa-check"></i><b>1.4</b> How to read this book</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-started-with-r-and-the-namcs-data.html"><a href="getting-started-with-r-and-the-namcs-data.html"><i class="fa fa-check"></i><b>2</b> Getting started with R and the NAMCS data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="getting-started-with-r-and-the-namcs-data.html"><a href="getting-started-with-r-and-the-namcs-data.html#r-rstudio-and-the-tidyverse"><i class="fa fa-check"></i><b>2.1</b> R, RStudio, and the tidyverse</a></li>
<li class="chapter" data-level="2.2" data-path="getting-started-with-r-and-the-namcs-data.html"><a href="getting-started-with-r-and-the-namcs-data.html#the-namcs-teaching-cohorts"><i class="fa fa-check"></i><b>2.2</b> The NAMCS teaching cohorts</a></li>
<li class="chapter" data-level="2.3" data-path="getting-started-with-r-and-the-namcs-data.html"><a href="getting-started-with-r-and-the-namcs-data.html#plotting-with-ggplot2"><i class="fa fa-check"></i><b>2.3</b> Plotting with ggplot2</a></li>
<li class="chapter" data-level="2.4" data-path="getting-started-with-r-and-the-namcs-data.html"><a href="getting-started-with-r-and-the-namcs-data.html#your-first-reusable-functions-table-1"><i class="fa fa-check"></i><b>2.4</b> Your first reusable functions: Table 1</a></li>
<li class="chapter" data-level="2.5" data-path="getting-started-with-r-and-the-namcs-data.html"><a href="getting-started-with-r-and-the-namcs-data.html#exercises"><i class="fa fa-check"></i><b>2.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="potential-outcomes-and-causal-effects.html"><a href="potential-outcomes-and-causal-effects.html"><i class="fa fa-check"></i><b>3</b> Potential outcomes and causal effects</a>
<ul>
<li class="chapter" data-level="3.1" data-path="potential-outcomes-and-causal-effects.html"><a href="potential-outcomes-and-causal-effects.html#two-futures-for-every-patient"><i class="fa fa-check"></i><b>3.1</b> Two futures for every patient</a></li>
<li class="chapter" data-level="3.2" data-path="potential-outcomes-and-causal-effects.html"><a href="potential-outcomes-and-causal-effects.html#simulating-both-potential-outcomes"><i class="fa fa-check"></i><b>3.2</b> Simulating both potential outcomes</a></li>
<li class="chapter" data-level="3.3" data-path="potential-outcomes-and-causal-effects.html"><a href="potential-outcomes-and-causal-effects.html#average-causal-effects-and-estimands"><i class="fa fa-check"></i><b>3.3</b> Average causal effects and estimands</a></li>
<li class="chapter" data-level="3.4" data-path="potential-outcomes-and-causal-effects.html"><a href="potential-outcomes-and-causal-effects.html#the-identification-conditions"><i class="fa fa-check"></i><b>3.4</b> The identification conditions</a></li>
<li class="chapter" data-level="3.5" data-path="potential-outcomes-and-causal-effects.html"><a href="potential-outcomes-and-causal-effects.html#exercises-1"><i class="fa fa-check"></i><b>3.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="the-randomized-trial-as-the-benchmark.html"><a href="the-randomized-trial-as-the-benchmark.html"><i class="fa fa-check"></i><b>4</b> The randomized trial as the benchmark</a>
<ul>
<li class="chapter" data-level="4.1" data-path="the-randomized-trial-as-the-benchmark.html"><a href="the-randomized-trial-as-the-benchmark.html#why-randomization-works"><i class="fa fa-check"></i><b>4.1</b> Why randomization works</a></li>
<li class="chapter" data-level="4.2" data-path="the-randomized-trial-as-the-benchmark.html"><a href="the-randomized-trial-as-the-benchmark.html#intention-to-treat-and-per-protocol"><i class="fa fa-check"></i><b>4.2</b> Intention-to-treat and per-protocol</a></li>
<li class="chapter" data-level="4.3" data-path="the-randomized-trial-as-the-benchmark.html"><a href="the-randomized-trial-as-the-benchmark.html#the-target-trial"><i class="fa fa-check"></i><b>4.3</b> The target trial</a></li>
<li class="chapter" data-level="4.4" data-path="the-randomized-trial-as-the-benchmark.html"><a href="the-randomized-trial-as-the-benchmark.html#exercises-2"><i class="fa fa-check"></i><b>4.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="causal-diagrams.html"><a href="causal-diagrams.html"><i class="fa fa-check"></i><b>5</b> Causal diagrams</a>
<ul>
<li class="chapter" data-level="5.1" data-path="causal-diagrams.html"><a href="causal-diagrams.html#drawing-causal-assumptions"><i class="fa fa-check"></i><b>5.1</b> Drawing causal assumptions</a></li>
<li class="chapter" data-level="5.2" data-path="causal-diagrams.html"><a href="causal-diagrams.html#the-nsaidpud-diagram"><i class="fa fa-check"></i><b>5.2</b> The NSAID–PUD diagram</a></li>
<li class="chapter" data-level="5.3" data-path="causal-diagrams.html"><a href="causal-diagrams.html#confounders-colliders-and-mediators"><i class="fa fa-check"></i><b>5.3</b> Confounders, colliders, and mediators</a></li>
<li class="chapter" data-level="5.4" data-path="causal-diagrams.html"><a href="causal-diagrams.html#selection-bias-as-collider-stratification"><i class="fa fa-check"></i><b>5.4</b> Selection bias as collider stratification</a></li>
<li class="chapter" data-level="5.5" data-path="causal-diagrams.html"><a href="causal-diagrams.html#exercises-3"><i class="fa fa-check"></i><b>5.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="study-design-for-causal-questions.html"><a href="study-design-for-causal-questions.html"><i class="fa fa-check"></i><b>6</b> Study design for causal questions</a>
<ul>
<li class="chapter" data-level="6.1" data-path="study-design-for-causal-questions.html"><a href="study-design-for-causal-questions.html#design-before-analysis"><i class="fa fa-check"></i><b>6.1</b> Design before analysis</a></li>
<li class="chapter" data-level="6.2" data-path="study-design-for-causal-questions.html"><a href="study-design-for-causal-questions.html#new-user-designs"><i class="fa fa-check"></i><b>6.2</b> New-user designs</a></li>
<li class="chapter" data-level="6.3" data-path="study-design-for-causal-questions.html"><a href="study-design-for-causal-questions.html#active-comparator-designs"><i class="fa fa-check"></i><b>6.3</b> Active-comparator designs</a></li>
<li class="chapter" data-level="6.4" data-path="study-design-for-causal-questions.html"><a href="study-design-for-causal-questions.html#immortal-time-and-other-time-zero-problems"><i class="fa fa-check"></i><b>6.4</b> Immortal time and other time-zero problems</a></li>
<li class="chapter" data-level="6.5" data-path="study-design-for-causal-questions.html"><a href="study-design-for-causal-questions.html#exercises-4"><i class="fa fa-check"></i><b>6.5</b> Exercises</a></li>
</ul></li>
<li class="part"><span><b>II Core Methods</b></span></li>
<li class="chapter" data-level="7" data-path="outcome-regression-and-standardization.html"><a href="outcome-regression-and-standardization.html"><i class="fa fa-check"></i><b>7</b> Outcome regression and standardization</a>
<ul>
<li class="chapter" data-level="7.1" data-path="outcome-regression-and-standardization.html"><a href="outcome-regression-and-standardization.html#adjusting-with-regression"><i class="fa fa-check"></i><b>7.1</b> Adjusting with regression</a></li>
<li class="chapter" data-level="7.2" data-path="outcome-regression-and-standardization.html"><a href="outcome-regression-and-standardization.html#standardization-predict-then-average"><i class="fa fa-check"></i><b>7.2</b> Standardization: predict, then average</a></li>
<li class="chapter" data-level="7.3" data-path="outcome-regression-and-standardization.html"><a href="outcome-regression-and-standardization.html#the-bootstrap"><i class="fa fa-check"></i><b>7.3</b> The bootstrap</a></li>
<li class="chapter" data-level="7.4" data-path="outcome-regression-and-standardization.html"><a href="outcome-regression-and-standardization.html#effect-modification"><i class="fa fa-check"></i><b>7.4</b> Effect modification</a></li>
<li class="chapter" data-level="7.5" data-path="outcome-regression-and-standardization.html"><a href="outcome-regression-and-standardization.html#exercises-5"><i class="fa fa-check"></i><b>7.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="propensity-scores.html"><a href="propensity-scores.html"><i class="fa fa-check"></i><b>8</b> Propensity scores</a>
<ul>
<li class="chapter" data-level="8.1" data-path="propensity-scores.html"><a href="propensity-scores.html#one-number-that-summarizes-confounding"><i class="fa fa-check"></i><b>8.1</b> One number that summarizes confounding</a></li>
<li class="chapter" data-level="8.2" data-path="propensity-scores.html"><a href="propensity-scores.html#estimating-the-score"><i class="fa fa-check"></i><b>8.2</b> Estimating the score</a></li>
<li class="chapter" data-level="8.3" data-path="propensity-scores.html"><a href="propensity-scores.html#stratification"><i class="fa fa-check"></i><b>8.3</b> Stratification</a></li>
<li class="chapter" data-level="8.4" data-path="propensity-scores.html"><a href="propensity-scores.html#matching"><i class="fa fa-check"></i><b>8.4</b> Matching</a></li>
<li class="chapter" data-level="8.5" data-path="propensity-scores.html"><a href="propensity-scores.html#choosing-the-ps-model"><i class="fa fa-check"></i><b>8.5</b> Choosing the PS model</a></li>
<li class="chapter" data-level="8.6" data-path="propensity-scores.html"><a href="propensity-scores.html#exercises-6"><i class="fa fa-check"></i><b>8.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html"><i class="fa fa-check"></i><b>9</b> Inverse probability of treatment weighting</a>
<ul>
<li class="chapter" data-level="9.1" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#reweighting-to-a-pseudo-population"><i class="fa fa-check"></i><b>9.1</b> Reweighting to a pseudo-population</a></li>
<li class="chapter" data-level="9.2" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#building-the-weights"><i class="fa fa-check"></i><b>9.2</b> Building the weights</a></li>
<li class="chapter" data-level="9.3" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#estimating-the-effect"><i class="fa fa-check"></i><b>9.3</b> Estimating the effect</a></li>
<li class="chapter" data-level="9.4" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#truncation-and-diagnostics"><i class="fa fa-check"></i><b>9.4</b> Truncation and diagnostics</a></li>
<li class="chapter" data-level="9.5" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#standardized-mortality-ratio-weights"><i class="fa fa-check"></i><b>9.5</b> Standardized mortality ratio weights</a></li>
<li class="chapter" data-level="9.6" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#msms-and-where-weighting-shines"><i class="fa fa-check"></i><b>9.6</b> MSMs and where weighting shines</a></li>
<li class="chapter" data-level="9.7" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#three-estimators-one-estimand"><i class="fa fa-check"></i><b>9.7</b> Three estimators, one estimand</a></li>
<li class="chapter" data-level="9.8" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#exercises-7"><i class="fa fa-check"></i><b>9.8</b> Exercises</a></li>
</ul></li>
<li class="part"><span><b>III Time, Censoring, and Survival</b></span></li>
<li class="chapter" data-level="10" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html"><i class="fa fa-check"></i><b>10</b> Survival outcomes and censoring</a>
<ul>
<li class="chapter" data-level="10.1" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html#the-statin-question"><i class="fa fa-check"></i><b>10.1</b> The statin question</a></li>
<li class="chapter" data-level="10.2" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html#anatomy-of-time-to-event-data"><i class="fa fa-check"></i><b>10.2</b> Anatomy of time-to-event data</a></li>
<li class="chapter" data-level="10.3" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html#kaplanmeier"><i class="fa fa-check"></i><b>10.3</b> Kaplan–Meier</a></li>
<li class="chapter" data-level="10.4" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html#death-as-a-competing-risk"><i class="fa fa-check"></i><b>10.4</b> Death as a competing risk</a></li>
<li class="chapter" data-level="10.5" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html#risks-versus-hazards"><i class="fa fa-check"></i><b>10.5</b> Risks versus hazards</a></li>
<li class="chapter" data-level="10.6" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html#when-censoring-lies"><i class="fa fa-check"></i><b>10.6</b> When censoring lies</a></li>
<li class="chapter" data-level="10.7" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html#exercises-8"><i class="fa fa-check"></i><b>10.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="inverse-probability-of-censoring-weights.html"><a href="inverse-probability-of-censoring-weights.html"><i class="fa fa-check"></i><b>11</b> Inverse probability of censoring weights</a>
<ul>
<li class="chapter" data-level="11.1" data-path="inverse-probability-of-censoring-weights.html"><a href="inverse-probability-of-censoring-weights.html#weighting-returns"><i class="fa fa-check"></i><b>11.1</b> Weighting returns</a></li>
<li class="chapter" data-level="11.2" data-path="inverse-probability-of-censoring-weights.html"><a href="inverse-probability-of-censoring-weights.html#person-period-data"><i class="fa fa-check"></i><b>11.2</b> Person-period data</a></li>
<li class="chapter" data-level="11.3" data-path="inverse-probability-of-censoring-weights.html"><a href="inverse-probability-of-censoring-weights.html#building-censoring-weights"><i class="fa fa-check"></i><b>11.3</b> Building censoring weights</a></li>
<li class="chapter" data-level="11.4" data-path="inverse-probability-of-censoring-weights.html"><a href="inverse-probability-of-censoring-weights.html#weight-diagnostics"><i class="fa fa-check"></i><b>11.4</b> Weight diagnostics</a></li>
<li class="chapter" data-level="11.5" data-path="inverse-probability-of-censoring-weights.html"><a href="inverse-probability-of-censoring-weights.html#did-it-matter"><i class="fa fa-check"></i><b>11.5</b> Did it matter?</a></li>
<li class="chapter" data-level="11.6" data-path="inverse-probability-of-censoring-weights.html"><a href="inverse-probability-of-censoring-weights.html#exercises-9"><i class="fa fa-check"></i><b>11.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="clone-censor-weight.html"><a href="clone-censor-weight.html"><i class="fa fa-check"></i><b>12</b> Clone-censor-weight</a>
<ul>
<li class="chapter" data-level="12.1" data-path="clone-censor-weight.html"><a href="clone-censor-weight.html#from-point-treatments-to-treatment-strategies"><i class="fa fa-check"></i><b>12.1</b> From point treatments to treatment strategies</a></li>
<li class="chapter" data-level="12.2" data-path="clone-censor-weight.html"><a href="clone-censor-weight.html#the-clone-censor-weight-recipe"><i class="fa fa-check"></i><b>12.2</b> The clone-censor-weight recipe</a></li>
<li class="chapter" data-level="12.3" data-path="clone-censor-weight.html"><a href="clone-censor-weight.html#deviation-in-the-statin-cohort"><i class="fa fa-check"></i><b>12.3</b> Deviation in the statin cohort</a></li>
<li class="chapter" data-level="12.4" data-path="clone-censor-weight.html"><a href="clone-censor-weight.html#estimating-per-protocol-risk-curves"><i class="fa fa-check"></i><b>12.4</b> Estimating per-protocol risk curves</a></li>
<li class="chapter" data-level="12.5" data-path="clone-censor-weight.html"><a href="clone-censor-weight.html#interpreting-the-per-protocol-effect"><i class="fa fa-check"></i><b>12.5</b> Interpreting the per-protocol effect</a></li>
<li class="chapter" data-level="12.6" data-path="clone-censor-weight.html"><a href="clone-censor-weight.html#exercises-10"><i class="fa fa-check"></i><b>12.6</b> Exercises</a></li>
</ul></li>
<li class="part"><span><b>IV Beyond Exchangeability</b></span></li>
<li class="chapter" data-level="13" data-path="instrumental-variables.html"><a href="instrumental-variables.html"><i class="fa fa-check"></i><b>13</b> Instrumental variables</a>
<ul>
<li class="chapter" data-level="13.1" data-path="instrumental-variables.html"><a href="instrumental-variables.html#when-exchangeability-fails"><i class="fa fa-check"></i><b>13.1</b> When exchangeability fails</a></li>
<li class="chapter" data-level="13.2" data-path="instrumental-variables.html"><a href="instrumental-variables.html#provider-preference-as-an-instrument"><i class="fa fa-check"></i><b>13.2</b> Provider preference as an instrument</a></li>
<li class="chapter" data-level="13.3" data-path="instrumental-variables.html"><a href="instrumental-variables.html#the-wald-and-two-stage-estimators"><i class="fa fa-check"></i><b>13.3</b> The Wald and two-stage estimators</a></li>
<li class="chapter" data-level="13.4" data-path="instrumental-variables.html"><a href="instrumental-variables.html#interpreting-the-late"><i class="fa fa-check"></i><b>13.4</b> Interpreting the LATE</a></li>
<li class="chapter" data-level="13.5" data-path="instrumental-variables.html"><a href="instrumental-variables.html#exercises-11"><i class="fa fa-check"></i><b>13.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="sensitivity-analysis.html"><a href="sensitivity-analysis.html"><i class="fa fa-check"></i><b>14</b> Sensitivity analysis</a>
<ul>
<li class="chapter" data-level="14.1" data-path="sensitivity-analysis.html"><a href="sensitivity-analysis.html#what-we-assumed-and-cannot-check"><i class="fa fa-check"></i><b>14.1</b> What we assumed and cannot check</a></li>
<li class="chapter" data-level="14.2" data-path="sensitivity-analysis.html"><a href="sensitivity-analysis.html#external-adjustment"><i class="fa fa-check"></i><b>14.2</b> External adjustment</a></li>
<li class="chapter" data-level="14.3" data-path="sensitivity-analysis.html"><a href="sensitivity-analysis.html#the-e-value"><i class="fa fa-check"></i><b>14.3</b> The E-value</a></li>
<li class="chapter" data-level="14.4" data-path="sensitivity-analysis.html"><a href="sensitivity-analysis.html#negative-control-outcomes"><i class="fa fa-check"></i><b>14.4</b> Negative control outcomes</a></li>
<li class="chapter" data-level="14.5" data-path="sensitivity-analysis.html"><a href="sensitivity-analysis.html#reporting-a-causal-analysis"><i class="fa fa-check"></i><b>14.5</b> Reporting a causal analysis</a></li>
<li class="chapter" data-level="14.6" data-path="sensitivity-analysis.html"><a href="sensitivity-analysis.html#exercises-12"><i class="fa fa-check"></i><b>14.6</b> Exercises</a></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="r-and-rstudio-setup.html"><a href="r-and-rstudio-setup.html"><i class="fa fa-check"></i><b>A</b> R and RStudio setup</a>
<ul>
<li class="chapter" data-level="A.1" data-path="r-and-rstudio-setup.html"><a href="r-and-rstudio-setup.html#installing-r-and-rstudio"><i class="fa fa-check"></i><b>A.1</b> Installing R and RStudio</a></li>
<li class="chapter" data-level="A.2" data-path="r-and-rstudio-setup.html"><a href="r-and-rstudio-setup.html#installing-the-packages-this-book-uses"><i class="fa fa-check"></i><b>A.2</b> Installing the packages this book uses</a></li>
<li class="chapter" data-level="A.3" data-path="r-and-rstudio-setup.html"><a href="r-and-rstudio-setup.html#installing-the-namcs-teaching-package"><i class="fa fa-check"></i><b>A.3</b> Installing the NAMCS teaching package</a></li>
<li class="chapter" data-level="A.4" data-path="r-and-rstudio-setup.html"><a href="r-and-rstudio-setup.html#loading-everything-a-chapter-needs"><i class="fa fa-check"></i><b>A.4</b> Loading everything a chapter needs</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="namcs-codebook.html"><a href="namcs-codebook.html"><i class="fa fa-check"></i><b>B</b> NAMCS codebook</a>
<ul>
<li class="chapter" data-level="B.1" data-path="namcs-codebook.html"><a href="namcs-codebook.html#the-nsaid-cohort-ns"><i class="fa fa-check"></i><b>B.1</b> The NSAID cohort (<code>ns</code>)</a></li>
<li class="chapter" data-level="B.2" data-path="namcs-codebook.html"><a href="namcs-codebook.html#the-statin-cohort-sta"><i class="fa fa-check"></i><b>B.2</b> The statin cohort (<code>sta</code>)</a></li>
<li class="chapter" data-level="B.3" data-path="namcs-codebook.html"><a href="namcs-codebook.html#a-note-on-the-outcomes"><i class="fa fa-check"></i><b>B.3</b> A note on the outcomes</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="the-estimator-toolkit.html"><a href="the-estimator-toolkit.html"><i class="fa fa-check"></i><b>C</b> The estimator toolkit</a></li>
<li class="chapter" data-level="D" data-path="generalized-linear-models-for-causal-contrasts.html"><a href="generalized-linear-models-for-causal-contrasts.html"><i class="fa fa-check"></i><b>D</b> Generalized linear models for causal contrasts</a></li>
<li class="chapter" data-level="E" data-path="a-bridge-to-cox-regression.html"><a href="a-bridge-to-cox-regression.html"><i class="fa fa-check"></i><b>E</b> A bridge to Cox regression</a></li>
<li class="chapter" data-level="F" data-path="course-map-phs-921.html"><a href="course-map-phs-921.html"><i class="fa fa-check"></i><b>F</b> Course map: PHS 921</a></li>
<li class="chapter" data-level="G" data-path="further-reading.html"><a href="further-reading.html"><i class="fa fa-check"></i><b>G</b> Further reading</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Causal Inference in Epidemiology Using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="instrumental-variables" class="section level1 hasAnchor" number="13">
<h1><span class="header-section-number">Chapter 13</span> Instrumental variables<a href="instrumental-variables.html#instrumental-variables" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Parts II and III differed in almost every mechanical detail, setting
standardization against weighting, point outcomes against time to event,
and baseline treatment against sustained strategies, and yet they agreed
on a single premise. Every estimator assumed that within levels of the
covariates we happened to record, treated and untreated patients were
exchangeable.
Part IV asks what remains available when that premise is precisely the
thing we doubt. This chapter looks for variation in treatment we can
argue is as good as randomly assigned even though the treatment itself
plainly is not. Chapter 14 takes the opposite tack, and
asks how badly exchangeability would have to fail before a finding
reversed.</p>
<div id="when-exchangeability-fails" class="section level2 hasAnchor" number="13.1">
<h2><span class="header-section-number">13.1</span> When exchangeability fails<a href="instrumental-variables.html#when-exchangeability-fails" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The bargain we have been striking all along is that if we measure enough
covariates, treatment is as good as randomized within their levels, and
it is a bargain we can never audit. Chapter 8’s balance diagnostics
confirm that the covariates we recorded are balanced; they are silent
about the ones we did not. When a clinician chooses a Cox-2 selective
agent because a patient looks frail in a way no billing code captures, no
amount of adjustment for the codes we do have will repair the comparison.</p>
<p>An <strong>instrumental variable</strong> offers a different bargain, and one whose
untestable content is differently placed rather than weaker. We
look for a variable <span class="math inline">\(Z\)</span> that shifts treatment for reasons that have
nothing to do with prognosis, and we use only the part of the variation
in treatment that <span class="math inline">\(Z\)</span> explains. Three conditions define such a variable,
stated here as Hernán and Robins (2006) stated them for
epidemiologists.</p>
<ol style="list-style-type: decimal">
<li><strong>Relevance.</strong> <span class="math inline">\(Z\)</span> is associated with treatment <span class="math inline">\(A\)</span>. This is the one
condition the data can speak to.</li>
<li><strong>Exclusion restriction.</strong> <span class="math inline">\(Z\)</span> affects the outcome <span class="math inline">\(Y\)</span> only through
<span class="math inline">\(A\)</span>. There is no arrow from <span class="math inline">\(Z\)</span> to <span class="math inline">\(Y\)</span> that bypasses treatment.</li>
<li><strong>Instrument exchangeability.</strong> Nothing points into both <span class="math inline">\(Z\)</span> and <span class="math inline">\(Y\)</span> —
no backdoor path connects the instrument to the outcome, either
unconditionally or after conditioning on measured covariates <span class="math inline">\(L\)</span>. The
instrument is itself unconfounded.</li>
</ol>
<p>Conditions 2 and 3 are assumptions in the same unverifiable sense that
conditional exchangeability was; we have moved the untestable content
rather than eliminated it. What we gain is that the assumptions now
concern a variable we may know something about institutionally, rather
than the completeness of a covariate list.</p>
<p>The three conditions together do not identify an effect; they bound one,
with bounds given by Manski (1990) and sharpened by Balke and Pearl
(1997), which are often wide and rarely reported. For a point estimate a
fourth assumption is needed, and there are two conventional choices.
Under <strong>effect homogeneity</strong> — the effect of <span class="math inline">\(A\)</span> on <span class="math inline">\(Y\)</span> is constant
across patients, or at least uncorrelated with how strongly <span class="math inline">\(Z\)</span> moves
their treatment — the instrument identifies the average treatment effect.
Under <strong>monotonicity</strong> — no patient’s treatment is pushed in the opposite
direction to everyone else’s by the instrument — it identifies the
average effect among those patients whose treatment the instrument
actually moved. That second quantity is the <strong>local average treatment
effect</strong>, and it is the one we will ultimately estimate.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="instrumental-variables.html#cb117-1" tabindex="-1"></a><span class="fu">library</span>(ggdag)</span>
<span id="cb117-2"><a href="instrumental-variables.html#cb117-2" tabindex="-1"></a>dag_iv <span class="ot">&lt;-</span> <span class="fu">dagify</span>(</span>
<span id="cb117-3"><a href="instrumental-variables.html#cb117-3" tabindex="-1"></a>  pud  <span class="sc">~</span> cox2 <span class="sc">+</span> u,</span>
<span id="cb117-4"><a href="instrumental-variables.html#cb117-4" tabindex="-1"></a>  cox2 <span class="sc">~</span> pref <span class="sc">+</span> u,</span>
<span id="cb117-5"><a href="instrumental-variables.html#cb117-5" tabindex="-1"></a>  <span class="at">exposure =</span> <span class="st">&quot;cox2&quot;</span>,</span>
<span id="cb117-6"><a href="instrumental-variables.html#cb117-6" tabindex="-1"></a>  <span class="at">outcome  =</span> <span class="st">&quot;pud&quot;</span>,</span>
<span id="cb117-7"><a href="instrumental-variables.html#cb117-7" tabindex="-1"></a>  <span class="at">latent   =</span> <span class="st">&quot;u&quot;</span>,</span>
<span id="cb117-8"><a href="instrumental-variables.html#cb117-8" tabindex="-1"></a>  <span class="at">labels =</span> <span class="fu">c</span>(<span class="at">pref =</span> <span class="st">&quot;Physician preference&quot;</span>, <span class="at">cox2 =</span> <span class="st">&quot;Cox-2 selective&quot;</span>,</span>
<span id="cb117-9"><a href="instrumental-variables.html#cb117-9" tabindex="-1"></a>             <span class="at">pud =</span> <span class="st">&quot;Peptic ulcer&quot;</span>, <span class="at">u =</span> <span class="st">&quot;Unmeasured confounders&quot;</span>)</span>
<span id="cb117-10"><a href="instrumental-variables.html#cb117-10" tabindex="-1"></a>)</span>
<span id="cb117-11"><a href="instrumental-variables.html#cb117-11" tabindex="-1"></a><span class="fu">ggdag</span>(dag_iv, <span class="at">text =</span> <span class="cn">FALSE</span>, <span class="at">use_labels =</span> <span class="st">&quot;label&quot;</span>) <span class="sc">+</span> <span class="fu">theme_dag</span>()</span></code></pre></div>
<p><img src="causal-inference-epi-r_files/figure-html/ch13-iv-dag-1.png" alt="" width="672" /></p>
<p>The diagram sets out the whole method in four nodes. The unmeasured <span class="math inline">\(U\)</span>
points at both <code>cox2</code> and <code>pud</code>, so the backdoor path that ruined the crude
comparison is still open and no adjustment set closes it. But <code>pref</code> has
exactly one arrow out of it, into <code>cox2</code>, and nothing pointing in from
<span class="math inline">\(U\)</span>. The only way <code>pref</code> and <code>pud</code> can be associated is along
<code>pref -&gt; cox2 -&gt; pud</code>, so any association we observe between them must
be the drug’s effect, scaled down by how much of <code>cox2</code> the instrument
controls. Rescaling by that amount is what an IV estimator does. Two of
the conditions appear in the diagram only as missing arrows: the absent
<code>pref -&gt; pud</code> arrow is the exclusion restriction, and the absent
<code>u -&gt; pref</code> arrow is instrument exchangeability.</p>
</div>
<div id="provider-preference-as-an-instrument" class="section level2 hasAnchor" number="13.2">
<h2><span class="header-section-number">13.2</span> Provider preference as an instrument<a href="instrumental-variables.html#provider-preference-as-an-instrument" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Physicians differ in prescribing habits for reasons that outlive any
individual patient, including training, detailing, formulary, and
temperament. Two patients with identical records who walk into different
offices may
receive different drugs, and the difference is attributable to the office
rather than to the patient. That is the intuition behind <strong>provider
preference</strong> as an instrument: we take a physician’s prescribing
tendency, estimated from her <em>other</em> patients, as an assigned nudge
toward one drug or the other.</p>
<p>The leave-one-out construction matters. If a physician’s preference were
computed from all her visits including the index one, a patient’s own
treatment would contribute <span class="math inline">\(1/n\)</span> of her physician’s score, and the first
stage would be mechanically positive even for a physician with no habit
at all. Excluding the index visit removes that arithmetic artifact, so
whatever association survives reflects the habit and not the patient.</p>
<p>The original implementation of this idea (Brookhart, Wang, Solomon, and
Schneeweiss 2006) used a lag-1 variant, in which the instrument was what
the physician prescribed to her <em>previous</em> patient. The leave-one-out
mean we use here is the same instrument in spirit, since both are proxies
for a prescribing preference the patient did not choose, although it
draws on all of the physician’s other patients rather than one, and so
uses more of the information each physician’s panel contains.</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="instrumental-variables.html#cb118-1" tabindex="-1"></a>ns_iv <span class="ot">&lt;-</span> ns <span class="sc">|&gt;</span></span>
<span id="cb118-2"><a href="instrumental-variables.html#cb118-2" tabindex="-1"></a>  <span class="fu">group_by</span>(phycode) <span class="sc">|&gt;</span></span>
<span id="cb118-3"><a href="instrumental-variables.html#cb118-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">n_visits =</span> <span class="fu">n</span>(),</span>
<span id="cb118-4"><a href="instrumental-variables.html#cb118-4" tabindex="-1"></a>         <span class="at">pref =</span> (<span class="fu">sum</span>(cox2_init) <span class="sc">-</span> cox2_init) <span class="sc">/</span> (n_visits <span class="sc">-</span> <span class="dv">1</span>)) <span class="sc">|&gt;</span></span>
<span id="cb118-5"><a href="instrumental-variables.html#cb118-5" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb118-6"><a href="instrumental-variables.html#cb118-6" tabindex="-1"></a>  <span class="fu">filter</span>(n_visits <span class="sc">&gt;=</span> <span class="dv">2</span>)</span></code></pre></div>
<p>The filter is not a formality. Of 1518 physicians, only
690 contribute two or more visits; the rest have no other
patient from whom a preference could be computed, since <code>n_visits - 1</code> is
zero and the score undefined. The cohort falls from
2882 visits to 2054, carrying
156 Cox-2 initiators and 207 ulcer
cases. This is the first cost of the method, paid before any estimation,
since an IV analysis buys its differently placed assumptions with data.</p>
<p>The distribution is heavily skewed. Cox-2 initiation is uncommon and most
physicians in a panel of two to ten visits prescribed none, so <code>pref</code> is
exactly zero for 1766 of the 2054
visits; only 288 patients saw a physician who prescribed a
Cox-2 drug to anyone else we observe.</p>
<p>Relevance we can check directly.</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="instrumental-variables.html#cb119-1" tabindex="-1"></a>first_stage <span class="ot">&lt;-</span> <span class="fu">lm</span>(cox2_init <span class="sc">~</span> pref, <span class="at">data =</span> ns_iv)</span>
<span id="cb119-2"><a href="instrumental-variables.html#cb119-2" tabindex="-1"></a><span class="fu">summary</span>(first_stage)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = cox2_init ~ pref, data = ns_iv)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.30239 -0.05734 -0.05734 -0.05734  0.94266 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 0.057338   0.006052   9.474   &lt;2e-16 ***
## pref        0.245047   0.025866   9.474   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2594 on 2052 degrees of freedom
## Multiple R-squared:  0.04191,    Adjusted R-squared:  0.04144 
## F-statistic: 89.75 on 1 and 2052 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Moving from a physician who prescribed a Cox-2 agent to none of her
other patients to one who prescribed it to all of them raises this
patient’s probability of receiving one by
24.5 percentage points
(SE 2.6), with an <span class="math inline">\(F\)</span> statistic of
90 — well past the conventional
rule-of-thumb threshold of 10. Adding <code>ns_covs</code> to the first stage barely
touches it: the partial <span class="math inline">\(F\)</span> for <code>pref</code> is
80. Physician habit therefore does predict
prescribing, which is the least we should demand of an instrument.</p>
<p>The second and third conditions cannot be checked, but one of their
implications can be inspected. If the instrument is assigned for reasons
unrelated to the patient, patient characteristics should be <em>more</em>
balanced across levels of the instrument than across levels of treatment.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="instrumental-variables.html#cb121-1" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;R/table1.R&quot;</span>)</span>
<span id="cb121-2"><a href="instrumental-variables.html#cb121-2" tabindex="-1"></a>ns_iv <span class="ot">&lt;-</span> ns_iv <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">pref_any =</span> <span class="fu">as.integer</span>(pref <span class="sc">&gt;</span> <span class="dv">0</span>))</span>
<span id="cb121-3"><a href="instrumental-variables.html#cb121-3" tabindex="-1"></a></span>
<span id="cb121-4"><a href="instrumental-variables.html#cb121-4" tabindex="-1"></a>by_both <span class="ot">&lt;-</span> <span class="cf">function</span>(f, vars) {</span>
<span id="cb121-5"><a href="instrumental-variables.html#cb121-5" tabindex="-1"></a>  <span class="fu">bind_rows</span>(</span>
<span id="cb121-6"><a href="instrumental-variables.html#cb121-6" tabindex="-1"></a>    <span class="st">`</span><span class="at">Treatment: nonselective / Cox-2</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">f</span>(ns_iv, vars, <span class="st">&quot;cox2_init&quot;</span>),</span>
<span id="cb121-7"><a href="instrumental-variables.html#cb121-7" tabindex="-1"></a>    <span class="st">`</span><span class="at">Instrument: pref = 0 / pref &gt; 0</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">f</span>(ns_iv, vars, <span class="st">&quot;pref_any&quot;</span>),</span>
<span id="cb121-8"><a href="instrumental-variables.html#cb121-8" tabindex="-1"></a>    <span class="at">.id =</span> <span class="st">&quot;contrast&quot;</span></span>
<span id="cb121-9"><a href="instrumental-variables.html#cb121-9" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb121-10"><a href="instrumental-variables.html#cb121-10" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="at">group_0 =</span> <span class="st">`</span><span class="at">0</span><span class="st">`</span>, <span class="at">group_1 =</span> <span class="st">`</span><span class="at">1</span><span class="st">`</span>)</span>
<span id="cb121-11"><a href="instrumental-variables.html#cb121-11" tabindex="-1"></a>}</span>
<span id="cb121-12"><a href="instrumental-variables.html#cb121-12" tabindex="-1"></a></span>
<span id="cb121-13"><a href="instrumental-variables.html#cb121-13" tabindex="-1"></a><span class="fu">by_both</span>(table1_continuous, <span class="st">&quot;age&quot;</span>) <span class="sc">|&gt;</span> knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">contrast</th>
<th align="left">variable</th>
<th align="left">group_0</th>
<th align="left">group_1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Treatment: nonselective / Cox-2</td>
<td align="left">age</td>
<td align="left">46.8 (16.5)</td>
<td align="left">52.0 (15.5)</td>
</tr>
<tr class="even">
<td align="left">Instrument: pref = 0 / pref &gt; 0</td>
<td align="left">age</td>
<td align="left">46.9 (16.5)</td>
<td align="left">48.7 (16.3)</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="instrumental-variables.html#cb122-1" tabindex="-1"></a><span class="fu">by_both</span>(table1_categorical, <span class="fu">c</span>(<span class="st">&quot;arthritis&quot;</span>, <span class="st">&quot;year&quot;</span>)) <span class="sc">|&gt;</span> knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code></pre></div>
<table>
<colgroup>
<col width="43%" />
<col width="13%" />
<col width="8%" />
<col width="17%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">contrast</th>
<th align="left">variable</th>
<th align="left">level</th>
<th align="left">group_0</th>
<th align="left">group_1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Treatment: nonselective / Cox-2</td>
<td align="left">arthritis</td>
<td align="left">No</td>
<td align="left">1299 (68.4%)</td>
<td align="left">81 (51.9%)</td>
</tr>
<tr class="even">
<td align="left">Treatment: nonselective / Cox-2</td>
<td align="left">arthritis</td>
<td align="left">Yes</td>
<td align="left">599 (31.6%)</td>
<td align="left">75 (48.1%)</td>
</tr>
<tr class="odd">
<td align="left">Treatment: nonselective / Cox-2</td>
<td align="left">year</td>
<td align="left">2005</td>
<td align="left">301 (15.9%)</td>
<td align="left">40 (25.6%)</td>
</tr>
<tr class="even">
<td align="left">Treatment: nonselective / Cox-2</td>
<td align="left">year</td>
<td align="left">2006</td>
<td align="left">412 (21.7%)</td>
<td align="left">39 (25.0%)</td>
</tr>
<tr class="odd">
<td align="left">Treatment: nonselective / Cox-2</td>
<td align="left">year</td>
<td align="left">2007</td>
<td align="left">399 (21.0%)</td>
<td align="left">28 (17.9%)</td>
</tr>
<tr class="even">
<td align="left">Treatment: nonselective / Cox-2</td>
<td align="left">year</td>
<td align="left">2008</td>
<td align="left">358 (18.9%)</td>
<td align="left">29 (18.6%)</td>
</tr>
<tr class="odd">
<td align="left">Treatment: nonselective / Cox-2</td>
<td align="left">year</td>
<td align="left">2009</td>
<td align="left">428 (22.6%)</td>
<td align="left">20 (12.8%)</td>
</tr>
<tr class="even">
<td align="left">Instrument: pref = 0 / pref &gt; 0</td>
<td align="left">arthritis</td>
<td align="left">No</td>
<td align="left">1211 (68.6%)</td>
<td align="left">169 (58.7%)</td>
</tr>
<tr class="odd">
<td align="left">Instrument: pref = 0 / pref &gt; 0</td>
<td align="left">arthritis</td>
<td align="left">Yes</td>
<td align="left">555 (31.4%)</td>
<td align="left">119 (41.3%)</td>
</tr>
<tr class="even">
<td align="left">Instrument: pref = 0 / pref &gt; 0</td>
<td align="left">year</td>
<td align="left">2005</td>
<td align="left">262 (14.8%)</td>
<td align="left">79 (27.4%)</td>
</tr>
<tr class="odd">
<td align="left">Instrument: pref = 0 / pref &gt; 0</td>
<td align="left">year</td>
<td align="left">2006</td>
<td align="left">385 (21.8%)</td>
<td align="left">66 (22.9%)</td>
</tr>
<tr class="even">
<td align="left">Instrument: pref = 0 / pref &gt; 0</td>
<td align="left">year</td>
<td align="left">2007</td>
<td align="left">378 (21.4%)</td>
<td align="left">49 (17.0%)</td>
</tr>
<tr class="odd">
<td align="left">Instrument: pref = 0 / pref &gt; 0</td>
<td align="left">year</td>
<td align="left">2008</td>
<td align="left">337 (19.1%)</td>
<td align="left">50 (17.4%)</td>
</tr>
<tr class="even">
<td align="left">Instrument: pref = 0 / pref &gt; 0</td>
<td align="left">year</td>
<td align="left">2009</td>
<td align="left">404 (22.9%)</td>
<td align="left">44 (15.3%)</td>
</tr>
</tbody>
</table>
<p>The comparison is partly reassuring and partly not, and the mixed result
is more instructive than a clean one would have been. On the clinical
covariates the instrument behaves as it should: age differs by
0.33 standardized units across treatment but
only 0.11 across the instrument, and
arthritis by 0.34 against
0.21. Across all
28 model terms the mean absolute standardized difference
is 0.113 for treatment and
0.102 for the instrument.</p>
<p>Calendar year is another matter, and the second table shows why. Cox-2
prescribing fell steadily over this period, from
11.7% of initiations in 2005
to 4.5% in 2009, and each
NAMCS physician contributes visits from a single survey year. A
high-preference physician is therefore disproportionately a 2005
physician, and the standardized difference for the 2005 indicator is
0.31 across the instrument against
0.24 across treatment — worse, not
better. Secular trends in ulcer diagnosis and management would then reach
the outcome without passing through this patient’s drug, violating the
exclusion restriction. Year is measured, so the repair is available: we
condition on it, and read the IV conditions as holding within levels of
<code>ns_covs</code> rather than unconditionally. The diagnostic did not validate
the instrument, although it did locate a specific threat and indicate
what to adjust for.</p>
</div>
<div id="the-wald-and-two-stage-estimators" class="section level2 hasAnchor" number="13.3">
<h2><span class="header-section-number">13.3</span> The Wald and two-stage estimators<a href="instrumental-variables.html#the-wald-and-two-stage-estimators" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>With a binary instrument the estimator is arithmetic. Suppose the
instrument shifts the treated fraction by <span class="math inline">\(\Delta_A\)</span> and the outcome risk
by <span class="math inline">\(\Delta_Y\)</span>. If the only route from instrument to outcome is through
treatment, then <span class="math inline">\(\Delta_Y = \beta \, \Delta_A\)</span>, where <span class="math inline">\(\beta\)</span> is the
effect of treatment on the outcome. Solving gives the <strong>Wald ratio</strong>,</p>
<p><span class="math display">\[\hat\beta = \frac{E[Y \mid Z = 1] - E[Y \mid Z = 0]}{E[A \mid Z = 1] - E[A \mid Z = 0]},\]</span></p>
<p>a difference in outcomes divided by a difference in treatments. We
dichotomize the instrument at the only cut point the data offer. Because
<code>pref</code> is exactly zero for six visits in seven, splitting at the median
with <code>ntile(pref, 2)</code> would divide the tied-at-zero mass arbitrarily and
produce two groups that barely differ in treatment; <code>pref &gt; 0</code> is the
substantive contrast.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="instrumental-variables.html#cb123-1" tabindex="-1"></a>wald_tab <span class="ot">&lt;-</span> ns_iv <span class="sc">|&gt;</span></span>
<span id="cb123-2"><a href="instrumental-variables.html#cb123-2" tabindex="-1"></a>  <span class="fu">group_by</span>(pref_any) <span class="sc">|&gt;</span></span>
<span id="cb123-3"><a href="instrumental-variables.html#cb123-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(), <span class="at">treated =</span> <span class="fu">mean</span>(cox2_init), <span class="at">risk =</span> <span class="fu">mean</span>(pud),</span>
<span id="cb123-4"><a href="instrumental-variables.html#cb123-4" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span>)</span>
<span id="cb123-5"><a href="instrumental-variables.html#cb123-5" tabindex="-1"></a>wald_tab <span class="sc">|&gt;</span> knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">4</span>)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">pref_any</th>
<th align="right">n</th>
<th align="right">treated</th>
<th align="right">risk</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="right">1766</td>
<td align="right">0.0606</td>
<td align="right">0.0985</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="right">288</td>
<td align="right">0.1701</td>
<td align="right">0.1146</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="instrumental-variables.html#cb124-1" tabindex="-1"></a>wald <span class="ot">&lt;-</span> <span class="fu">with</span>(wald_tab, <span class="fu">diff</span>(risk) <span class="sc">/</span> <span class="fu">diff</span>(treated))</span>
<span id="cb124-2"><a href="instrumental-variables.html#cb124-2" tabindex="-1"></a>wald</span></code></pre></div>
<pre><code>## [1] 0.1465595</code></pre>
<p>The instrument moves treatment by
11.0 percentage points and the outcome by
+1.6, so the ratio is
+14.7 percentage points. The numerator and denominator
are worth reading before the quotient: a +1.6-point
difference in ulcer risk between groups of 1766 and
288 patients is well within sampling variability, and dividing a noisy
small number by 0.11 multiplies the noise by nine.</p>
<p>The general form replaces the ratio with two regressions. Fit treatment
on the instrument, take the fitted values, and regress the outcome on
those — <strong>two-stage least squares</strong>, which reproduces the Wald ratio
exactly with a single binary instrument and generalizes to continuous
instruments and covariates.</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="instrumental-variables.html#cb126-1" tabindex="-1"></a>iv_estimator <span class="ot">&lt;-</span> <span class="cf">function</span>(data, instrument, treat, outcome, <span class="at">covs =</span> <span class="cn">NULL</span>,</span>
<span id="cb126-2"><a href="instrumental-variables.html#cb126-2" tabindex="-1"></a>                         <span class="at">n_boot =</span> <span class="dv">200</span>, <span class="at">conf_level =</span> <span class="fl">0.95</span>, <span class="at">seed =</span> <span class="cn">NULL</span>) {</span>
<span id="cb126-3"><a href="instrumental-variables.html#cb126-3" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(seed)) <span class="fu">set.seed</span>(seed)</span>
<span id="cb126-4"><a href="instrumental-variables.html#cb126-4" tabindex="-1"></a></span>
<span id="cb126-5"><a href="instrumental-variables.html#cb126-5" tabindex="-1"></a>  tsls <span class="ot">&lt;-</span> <span class="cf">function</span>(d) {</span>
<span id="cb126-6"><a href="instrumental-variables.html#cb126-6" tabindex="-1"></a>    s1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">reformulate</span>(<span class="fu">c</span>(instrument, covs), treat), <span class="at">data =</span> d)</span>
<span id="cb126-7"><a href="instrumental-variables.html#cb126-7" tabindex="-1"></a>    d<span class="sc">$</span>.that <span class="ot">&lt;-</span> <span class="fu">predict</span>(s1)</span>
<span id="cb126-8"><a href="instrumental-variables.html#cb126-8" tabindex="-1"></a>    <span class="fu">coef</span>(<span class="fu">lm</span>(<span class="fu">reformulate</span>(<span class="fu">c</span>(<span class="st">&quot;.that&quot;</span>, covs), outcome), <span class="at">data =</span> d))[<span class="st">&quot;.that&quot;</span>]</span>
<span id="cb126-9"><a href="instrumental-variables.html#cb126-9" tabindex="-1"></a>  }</span>
<span id="cb126-10"><a href="instrumental-variables.html#cb126-10" tabindex="-1"></a></span>
<span id="cb126-11"><a href="instrumental-variables.html#cb126-11" tabindex="-1"></a>  est <span class="ot">&lt;-</span> <span class="fu">tsls</span>(data)</span>
<span id="cb126-12"><a href="instrumental-variables.html#cb126-12" tabindex="-1"></a>  boot_est <span class="ot">&lt;-</span> <span class="fu">replicate</span>(n_boot, <span class="fu">tsls</span>(<span class="fu">slice_sample</span>(data, <span class="at">prop =</span> <span class="dv">1</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)))</span>
<span id="cb126-13"><a href="instrumental-variables.html#cb126-13" tabindex="-1"></a>  alpha <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> conf_level</span>
<span id="cb126-14"><a href="instrumental-variables.html#cb126-14" tabindex="-1"></a></span>
<span id="cb126-15"><a href="instrumental-variables.html#cb126-15" tabindex="-1"></a>  <span class="fu">tibble</span>(</span>
<span id="cb126-16"><a href="instrumental-variables.html#cb126-16" tabindex="-1"></a>    <span class="at">estimate  =</span> <span class="fu">unname</span>(est),</span>
<span id="cb126-17"><a href="instrumental-variables.html#cb126-17" tabindex="-1"></a>    <span class="at">conf_low  =</span> <span class="fu">quantile</span>(boot_est, alpha <span class="sc">/</span> <span class="dv">2</span>),</span>
<span id="cb126-18"><a href="instrumental-variables.html#cb126-18" tabindex="-1"></a>    <span class="at">conf_high =</span> <span class="fu">quantile</span>(boot_est, <span class="dv">1</span> <span class="sc">-</span> alpha <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb126-19"><a href="instrumental-variables.html#cb126-19" tabindex="-1"></a>  )</span>
<span id="cb126-20"><a href="instrumental-variables.html#cb126-20" tabindex="-1"></a>}</span></code></pre></div>
<p>Two choices in that code are deliberate. The first stage is <code>lm()</code> even
though <code>cox2_init</code> is binary, where every instinct from Chapter 8 says
logistic regression. Substituting fitted probabilities from a
nonlinear first stage is the error known as the <strong>forbidden regression</strong>:
two-stage least squares is consistent because the first stage is a
<em>linear projection</em> of treatment onto the instrument and covariates,
which needs no model to be correct, whereas a logistic first stage
delivers usable fitted values only if the logistic model itself is right.</p>
<p>The second is the bootstrap. Reading the standard error off the
second-stage <code>lm()</code> would treat <code>.that</code> as data rather than as an
estimate, understating uncertainty; resampling propagates both stages,
and the <code>seed</code> argument makes a particular set of resamples
reproducible.</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="instrumental-variables.html#cb127-1" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;R/iv_estimator.R&quot;</span>)</span>
<span id="cb127-2"><a href="instrumental-variables.html#cb127-2" tabindex="-1"></a></span>
<span id="cb127-3"><a href="instrumental-variables.html#cb127-3" tabindex="-1"></a>iv_plain <span class="ot">&lt;-</span> <span class="fu">iv_estimator</span>(ns_iv, <span class="st">&quot;pref&quot;</span>, <span class="st">&quot;cox2_init&quot;</span>, <span class="st">&quot;pud&quot;</span>, <span class="at">seed =</span> <span class="dv">1301</span>)</span>
<span id="cb127-4"><a href="instrumental-variables.html#cb127-4" tabindex="-1"></a>iv_adj   <span class="ot">&lt;-</span> <span class="fu">iv_estimator</span>(ns_iv, <span class="st">&quot;pref&quot;</span>, <span class="st">&quot;cox2_init&quot;</span>, <span class="st">&quot;pud&quot;</span>,</span>
<span id="cb127-5"><a href="instrumental-variables.html#cb127-5" tabindex="-1"></a>                         <span class="at">covs =</span> ns_covs, <span class="at">seed =</span> <span class="dv">1301</span>)</span>
<span id="cb127-6"><a href="instrumental-variables.html#cb127-6" tabindex="-1"></a><span class="fu">bind_rows</span>(<span class="at">unadjusted =</span> iv_plain, <span class="at">adjusted =</span> iv_adj, <span class="at">.id =</span> <span class="st">&quot;model&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb127-7"><a href="instrumental-variables.html#cb127-7" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">4</span>)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">model</th>
<th align="right">estimate</th>
<th align="right">conf_low</th>
<th align="right">conf_high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">unadjusted</td>
<td align="right">-0.0497</td>
<td align="right">-0.2802</td>
<td align="right">0.1532</td>
</tr>
<tr class="even">
<td align="left">adjusted</td>
<td align="right">-0.1471</td>
<td align="right">-0.4024</td>
<td align="right">0.0569</td>
</tr>
</tbody>
</table>
<p>Now the full comparison, with Part II’s estimates recomputed alongside.</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="instrumental-variables.html#cb128-1" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;R/standardize.R&quot;</span>); <span class="fu">source</span>(<span class="st">&quot;R/propensity.R&quot;</span>); <span class="fu">source</span>(<span class="st">&quot;R/iptw_estimator.R&quot;</span>)</span>
<span id="cb128-2"><a href="instrumental-variables.html#cb128-2" tabindex="-1"></a></span>
<span id="cb128-3"><a href="instrumental-variables.html#cb128-3" tabindex="-1"></a>ps_model <span class="ot">&lt;-</span> <span class="fu">reformulate</span>(ns_covs, <span class="st">&quot;cox2_init&quot;</span>)</span>
<span id="cb128-4"><a href="instrumental-variables.html#cb128-4" tabindex="-1"></a>crude <span class="ot">&lt;-</span> ns <span class="sc">|&gt;</span> <span class="fu">group_by</span>(cox2_init) <span class="sc">|&gt;</span> <span class="fu">summarise</span>(<span class="at">r =</span> <span class="fu">mean</span>(pud), <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(r)</span>
<span id="cb128-5"><a href="instrumental-variables.html#cb128-5" tabindex="-1"></a>std   <span class="ot">&lt;-</span> <span class="fu">standardize</span>(ns, <span class="fu">reformulate</span>(<span class="fu">c</span>(<span class="st">&quot;cox2_init&quot;</span>, ns_covs), <span class="st">&quot;pud&quot;</span>),</span>
<span id="cb128-6"><a href="instrumental-variables.html#cb128-6" tabindex="-1"></a>                     <span class="at">treat =</span> <span class="st">&quot;cox2_init&quot;</span>, <span class="at">n_boot =</span> <span class="dv">200</span>, <span class="at">seed =</span> <span class="dv">921</span>)</span>
<span id="cb128-7"><a href="instrumental-variables.html#cb128-7" tabindex="-1"></a>ipw   <span class="ot">&lt;-</span> <span class="fu">iptw_estimator</span>(ns, ps_model, <span class="at">outcome =</span> <span class="st">&quot;pud&quot;</span>, <span class="at">treat =</span> <span class="st">&quot;cox2_init&quot;</span>)</span>
<span id="cb128-8"><a href="instrumental-variables.html#cb128-8" tabindex="-1"></a>matched <span class="ot">&lt;-</span> <span class="fu">ps_match</span>(<span class="fu">est_ps</span>(ns, ps_model), <span class="at">treat =</span> <span class="st">&quot;cox2_init&quot;</span>, <span class="at">caliper =</span> <span class="fl">0.05</span>)</span>
<span id="cb128-9"><a href="instrumental-variables.html#cb128-9" tabindex="-1"></a>mr    <span class="ot">&lt;-</span> <span class="fu">tapply</span>(matched<span class="sc">$</span>pud, matched<span class="sc">$</span>cox2_init, mean)</span>
<span id="cb128-10"><a href="instrumental-variables.html#cb128-10" tabindex="-1"></a>iv_wald <span class="ot">&lt;-</span> <span class="fu">iv_estimator</span>(ns_iv, <span class="st">&quot;pref_any&quot;</span>, <span class="st">&quot;cox2_init&quot;</span>, <span class="st">&quot;pud&quot;</span>, <span class="at">seed =</span> <span class="dv">1301</span>)</span>
<span id="cb128-11"><a href="instrumental-variables.html#cb128-11" tabindex="-1"></a></span>
<span id="cb128-12"><a href="instrumental-variables.html#cb128-12" tabindex="-1"></a>get <span class="ot">&lt;-</span> <span class="cf">function</span>(d, key, col) d[[col]][d[[<span class="dv">1</span>]] <span class="sc">==</span> key]</span>
<span id="cb128-13"><a href="instrumental-variables.html#cb128-13" tabindex="-1"></a></span>
<span id="cb128-14"><a href="instrumental-variables.html#cb128-14" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb128-15"><a href="instrumental-variables.html#cb128-15" tabindex="-1"></a>  <span class="at">estimator =</span> <span class="fu">c</span>(<span class="st">&quot;Crude&quot;</span>, <span class="st">&quot;Standardization (Ch. 7)&quot;</span>, <span class="st">&quot;PS matching (Ch. 8)&quot;</span>,</span>
<span id="cb128-16"><a href="instrumental-variables.html#cb128-16" tabindex="-1"></a>                <span class="st">&quot;IPTW (Ch. 9)&quot;</span>, <span class="st">&quot;IV: Wald, pref &gt; 0&quot;</span>,</span>
<span id="cb128-17"><a href="instrumental-variables.html#cb128-17" tabindex="-1"></a>                <span class="st">&quot;IV: 2SLS, continuous pref&quot;</span>, <span class="st">&quot;IV: 2SLS + covariates&quot;</span>),</span>
<span id="cb128-18"><a href="instrumental-variables.html#cb128-18" tabindex="-1"></a>  <span class="at">estimand  =</span> <span class="fu">c</span>(<span class="st">&quot;none&quot;</span>, <span class="st">&quot;ATE&quot;</span>, <span class="st">&quot;ATT&quot;</span>, <span class="st">&quot;ATE&quot;</span>, <span class="st">&quot;LATE&quot;</span>, <span class="st">&quot;LATE&quot;</span>, <span class="st">&quot;LATE&quot;</span>),</span>
<span id="cb128-19"><a href="instrumental-variables.html#cb128-19" tabindex="-1"></a>  <span class="at">n         =</span> <span class="fu">c</span>(<span class="fu">nrow</span>(ns), <span class="fu">nrow</span>(ns), <span class="fu">nrow</span>(matched), <span class="fu">nrow</span>(ns), <span class="fu">rep</span>(<span class="fu">nrow</span>(ns_iv), <span class="dv">3</span>)),</span>
<span id="cb128-20"><a href="instrumental-variables.html#cb128-20" tabindex="-1"></a>  <span class="at">rd_pp =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">c</span>(crude[<span class="dv">2</span>] <span class="sc">-</span> crude[<span class="dv">1</span>], <span class="fu">get</span>(std, <span class="st">&quot;rd&quot;</span>, <span class="st">&quot;estimate&quot;</span>),</span>
<span id="cb128-21"><a href="instrumental-variables.html#cb128-21" tabindex="-1"></a>                  mr[[<span class="dv">2</span>]] <span class="sc">-</span> mr[[<span class="dv">1</span>]], <span class="fu">get</span>(ipw, <span class="st">&quot;cox2_init&quot;</span>, <span class="st">&quot;estimate&quot;</span>),</span>
<span id="cb128-22"><a href="instrumental-variables.html#cb128-22" tabindex="-1"></a>                  iv_wald<span class="sc">$</span>estimate, iv_plain<span class="sc">$</span>estimate, iv_adj<span class="sc">$</span>estimate),</span>
<span id="cb128-23"><a href="instrumental-variables.html#cb128-23" tabindex="-1"></a>  <span class="at">lower =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="fu">get</span>(std, <span class="st">&quot;rd&quot;</span>, <span class="st">&quot;conf_low&quot;</span>), <span class="cn">NA</span>,</span>
<span id="cb128-24"><a href="instrumental-variables.html#cb128-24" tabindex="-1"></a>                  <span class="fu">get</span>(ipw, <span class="st">&quot;cox2_init&quot;</span>, <span class="st">&quot;conf.low&quot;</span>),</span>
<span id="cb128-25"><a href="instrumental-variables.html#cb128-25" tabindex="-1"></a>                  iv_wald<span class="sc">$</span>conf_low, iv_plain<span class="sc">$</span>conf_low, iv_adj<span class="sc">$</span>conf_low),</span>
<span id="cb128-26"><a href="instrumental-variables.html#cb128-26" tabindex="-1"></a>  <span class="at">upper =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="fu">get</span>(std, <span class="st">&quot;rd&quot;</span>, <span class="st">&quot;conf_high&quot;</span>), <span class="cn">NA</span>,</span>
<span id="cb128-27"><a href="instrumental-variables.html#cb128-27" tabindex="-1"></a>                  <span class="fu">get</span>(ipw, <span class="st">&quot;cox2_init&quot;</span>, <span class="st">&quot;conf.high&quot;</span>),</span>
<span id="cb128-28"><a href="instrumental-variables.html#cb128-28" tabindex="-1"></a>                  iv_wald<span class="sc">$</span>conf_high, iv_plain<span class="sc">$</span>conf_high, iv_adj<span class="sc">$</span>conf_high)</span>
<span id="cb128-29"><a href="instrumental-variables.html#cb128-29" tabindex="-1"></a>) <span class="sc">|&gt;</span> knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">1</span>)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">estimator</th>
<th align="left">estimand</th>
<th align="right">n</th>
<th align="right">rd_pp</th>
<th align="right">lower</th>
<th align="right">upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Crude</td>
<td align="left">none</td>
<td align="right">2882</td>
<td align="right">2.7</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">Standardization (Ch. 7)</td>
<td align="left">ATE</td>
<td align="right">2882</td>
<td align="right">-0.6</td>
<td align="right">-3.8</td>
<td align="right">2.5</td>
</tr>
<tr class="odd">
<td align="left">PS matching (Ch. 8)</td>
<td align="left">ATT</td>
<td align="right">478</td>
<td align="right">-4.2</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">IPTW (Ch. 9)</td>
<td align="left">ATE</td>
<td align="right">2882</td>
<td align="right">-0.3</td>
<td align="right">-4.2</td>
<td align="right">3.6</td>
</tr>
<tr class="odd">
<td align="left">IV: Wald, pref &gt; 0</td>
<td align="left">LATE</td>
<td align="right">2054</td>
<td align="right">14.7</td>
<td align="right">-21.2</td>
<td align="right">56.2</td>
</tr>
<tr class="even">
<td align="left">IV: 2SLS, continuous pref</td>
<td align="left">LATE</td>
<td align="right">2054</td>
<td align="right">-5.0</td>
<td align="right">-28.0</td>
<td align="right">15.3</td>
</tr>
<tr class="odd">
<td align="left">IV: 2SLS + covariates</td>
<td align="left">LATE</td>
<td align="right">2054</td>
<td align="right">-14.7</td>
<td align="right">-40.2</td>
<td align="right">5.7</td>
</tr>
</tbody>
</table>
<p>The three IV rows should not be read as three answers; they are one
non-answer reported three ways. The continuous-instrument estimate is
-5.0 percentage points, the
covariate-adjusted version -14.7,
and the binary Wald ratio +14.7 — a change of
sign across two codings of the same instrument. Their intervals span
roughly 43 percentage points against
7.9 for IPTW on the same question, and they
include values that are arithmetically impossible: the ulcer risk among
nonselective initiators here is
9.9%, so a risk difference of
-28 points cannot occur. An
interval that contains impossible values is not informative about the
effect, whereas Part II’s estimates, whatever their residual confounding,
at least sit on the scale of the quantity they estimate.</p>
</div>
<div id="interpreting-the-late" class="section level2 hasAnchor" number="13.4">
<h2><span class="header-section-number">13.4</span> Interpreting the LATE<a href="instrumental-variables.html#interpreting-the-late" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Suppose the instrument were flawless and the sample large. What would we
have estimated? Take the binary Wald row first, where the answer is
cleanest. Under monotonicity, patients divide into three groups.
<strong>Always-takers</strong> receive the Cox-2 drug regardless of which physician
they see; <strong>never-takers</strong> receive the nonselective agent regardless; and
<strong>compliers</strong> receive whichever drug their physician’s habit favors. The
instrument carries no information about the first two groups, because
their treatment does not respond to it. The local average treatment
effect is the average effect among compliers alone.</p>
<p>The first stage measures how large that group is. Moving from a
zero-preference to a positive-preference physician shifts the treated
fraction by 11.0 points, so roughly one patient
in 9 is a complier —
about 225 of the 2054 in the cohort, among whom we
would expect on the order of 22
ulcer cases. That number, not 2054, is the effective size of
the Wald analysis, and it accounts for the intervals above better than
any other single quantity.</p>
<p>The continuous-<code>pref</code> rows, which carry the headline estimates, need one
further step of care, because with a many-valued instrument there is no
single complier group. A shift in preference from 0 to 0.25 moves one set
of patients and a shift from 0.5 to 0.75 moves another, and 2SLS under a
linear model returns a weighted average of these per-increment local
effects across the instrument’s support, weighted by how much treatment
each increment shifts (Angrist and Imbens 1995). The complier arithmetic
above is exact for the binary row and an illustration of the idea for the
others; no single describable subgroup sits behind that weighted average.</p>
<p>Compliers are a subgroup we cannot enumerate, since no patient is
labeled as one, and their clinical meaning depends on the instrument.
Here they are the patients whose prescription could genuinely have gone
either way.
The arthritic patient with a prior bleed, for whom a Cox-2 agent is
clearly indicated, is an always-taker, and the young patient with no GI
history who would receive ibuprofen from any physician is a never-taker; the complier
is the intermediate patient whose treatment tracked her physician’s
habit. Whether the average effect in that group is what a guideline
committee wants is worth asking explicitly, and the answer is often no.
The LATE is a third estimand, distinct from the ATE of Chapter 3 and the
ATT of Chapter 8, and defined by the instrument we happened to find.</p>
<p>Two caveats bound what this chapter has shown. The weak-instrument
literature warns that when the first stage is barely predictive, 2SLS is
biased toward the confounded estimate and its intervals undercover; the
<span class="math inline">\(F\)</span> statistic of 90 clears the usual threshold, so
that is not our leading problem, although the threshold assumes
independent observations, and <code>pref</code> varies at the physician level with
only 690 physicians contributing. <code>iv_estimator()</code> as written
resamples visits rather than physicians, so every interval in this
chapter is too narrow by an amount we have not measured, and clustering
at the physician level would widen all of them. Our leading problem is
nonetheless simpler, and not repairable by a
better estimator: the reduced-form association between instrument and
outcome is -0.012
(SE 0.030), indistinguishable from
zero, and dividing a null numerator by a small denominator yields a wide
interval around nothing.</p>
<p>The provider-preference instrument in these data is strong enough to be
worth constructing and transparent enough to audit, since the year
imbalance we found is itself a finding about the instrument, but the
analysis it yields is far too imprecise to settle the question. Although its non-contradiction of
the null is mildly informative as one line in a sensitivity table beside
Part II’s estimates, because it rests on different assumptions, it would
be indefensible as a headline result with the point estimate quoted and
the interval omitted.</p>
</div>
<div id="exercises-11" class="section level2 hasAnchor" number="13.5">
<h2><span class="header-section-number">13.5</span> Exercises<a href="instrumental-variables.html#exercises-11" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li>Rebuild the instrument requiring <code>n_visits &gt;= 3</code> instead of 2. Report
the resulting cohort size, the first-stage <span class="math inline">\(F\)</span>, and the IV estimate
with its interval. The score is measured from more visits and so is
less noisy, but fewer patients remain. Which effect dominates here,
and how would you preregister the threshold?</li>
<li>Compare <code>iv_estimator()</code> run with <code>covs = ns_covs</code> against the
unadjusted fit, and explain why covariates must appear in <em>both</em>
stages rather than only the second. Then remove <code>year</code> from <code>ns_covs</code>
and rerun. Given the imbalance documented above, how much of the
difference between the adjusted and unadjusted estimates is calendar
time?</li>
<li>Suppose physicians who favor Cox-2 agents also practice in
better-resourced settings, so their patients receive closer follow-up
and more attentive management of GI symptoms. Draw the DAG. Which of
the three IV conditions fails, in which direction would it bias the
estimate, and would conditioning on <code>ns_covs</code> help? Propose one
variable, measured or not, that would let you probe the assumption.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="clone-censor-weight.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="sensitivity-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": null,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
