<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 Inverse probability of treatment weighting | Causal Inference in Epidemiology Using R</title>
  <meta name="description" content="An introduction to causal inference with epidemiologic applications in R." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 Inverse probability of treatment weighting | Causal Inference in Epidemiology Using R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An introduction to causal inference with epidemiologic applications in R." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 Inverse probability of treatment weighting | Causal Inference in Epidemiology Using R" />
  
  <meta name="twitter:description" content="An introduction to causal inference with epidemiologic applications in R." />
  

<meta name="author" content="M. Alan Brookhart" />


<meta name="date" content="2026-08-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="propensity-scores.html"/>
<link rel="next" href="survival-outcomes-and-censoring.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Causal Inference in Epidemiology Using R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="0.1" data-path="preface.html"><a href="preface.html#who-this-book-is-for"><i class="fa fa-check"></i><b>0.1</b> Who this book is for</a></li>
<li class="chapter" data-level="0.2" data-path="preface.html"><a href="preface.html#how-the-book-works"><i class="fa fa-check"></i><b>0.2</b> How the book works</a></li>
<li class="chapter" data-level="0.3" data-path="preface.html"><a href="preface.html#software"><i class="fa fa-check"></i><b>0.3</b> Software</a></li>
</ul></li>
<li class="part"><span><b>I Foundations</b></span></li>
<li class="chapter" data-level="1" data-path="why.html"><a href="why.html"><i class="fa fa-check"></i><b>1</b> Why causal inference?</a>
<ul>
<li class="chapter" data-level="1.1" data-path="why.html"><a href="why.html#questions-epidemiology-cannot-answer-with-association-alone"><i class="fa fa-check"></i><b>1.1</b> Questions epidemiology cannot answer with association alone</a></li>
<li class="chapter" data-level="1.2" data-path="why.html"><a href="why.html#a-first-look-at-the-data"><i class="fa fa-check"></i><b>1.2</b> A first look at the data</a></li>
<li class="chapter" data-level="1.3" data-path="why.html"><a href="why.html#what-this-book-covers"><i class="fa fa-check"></i><b>1.3</b> What this book covers</a></li>
<li class="chapter" data-level="1.4" data-path="why.html"><a href="why.html#how-to-read-this-book"><i class="fa fa-check"></i><b>1.4</b> How to read this book</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-started-with-r-and-the-namcs-data.html"><a href="getting-started-with-r-and-the-namcs-data.html"><i class="fa fa-check"></i><b>2</b> Getting started with R and the NAMCS data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="getting-started-with-r-and-the-namcs-data.html"><a href="getting-started-with-r-and-the-namcs-data.html#r-rstudio-and-the-tidyverse"><i class="fa fa-check"></i><b>2.1</b> R, RStudio, and the tidyverse</a></li>
<li class="chapter" data-level="2.2" data-path="getting-started-with-r-and-the-namcs-data.html"><a href="getting-started-with-r-and-the-namcs-data.html#the-namcs-teaching-cohorts"><i class="fa fa-check"></i><b>2.2</b> The NAMCS teaching cohorts</a></li>
<li class="chapter" data-level="2.3" data-path="getting-started-with-r-and-the-namcs-data.html"><a href="getting-started-with-r-and-the-namcs-data.html#plotting-with-ggplot2"><i class="fa fa-check"></i><b>2.3</b> Plotting with ggplot2</a></li>
<li class="chapter" data-level="2.4" data-path="getting-started-with-r-and-the-namcs-data.html"><a href="getting-started-with-r-and-the-namcs-data.html#your-first-reusable-functions-table-1"><i class="fa fa-check"></i><b>2.4</b> Your first reusable functions: Table 1</a></li>
<li class="chapter" data-level="2.5" data-path="getting-started-with-r-and-the-namcs-data.html"><a href="getting-started-with-r-and-the-namcs-data.html#exercises"><i class="fa fa-check"></i><b>2.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="potential-outcomes-and-causal-effects.html"><a href="potential-outcomes-and-causal-effects.html"><i class="fa fa-check"></i><b>3</b> Potential outcomes and causal effects</a>
<ul>
<li class="chapter" data-level="3.1" data-path="potential-outcomes-and-causal-effects.html"><a href="potential-outcomes-and-causal-effects.html#two-futures-for-every-patient"><i class="fa fa-check"></i><b>3.1</b> Two futures for every patient</a></li>
<li class="chapter" data-level="3.2" data-path="potential-outcomes-and-causal-effects.html"><a href="potential-outcomes-and-causal-effects.html#simulating-both-potential-outcomes"><i class="fa fa-check"></i><b>3.2</b> Simulating both potential outcomes</a></li>
<li class="chapter" data-level="3.3" data-path="potential-outcomes-and-causal-effects.html"><a href="potential-outcomes-and-causal-effects.html#average-causal-effects-and-estimands"><i class="fa fa-check"></i><b>3.3</b> Average causal effects and estimands</a></li>
<li class="chapter" data-level="3.4" data-path="potential-outcomes-and-causal-effects.html"><a href="potential-outcomes-and-causal-effects.html#the-identification-conditions"><i class="fa fa-check"></i><b>3.4</b> The identification conditions</a></li>
<li class="chapter" data-level="3.5" data-path="potential-outcomes-and-causal-effects.html"><a href="potential-outcomes-and-causal-effects.html#exercises-1"><i class="fa fa-check"></i><b>3.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="the-randomized-trial-as-the-benchmark.html"><a href="the-randomized-trial-as-the-benchmark.html"><i class="fa fa-check"></i><b>4</b> The randomized trial as the benchmark</a>
<ul>
<li class="chapter" data-level="4.1" data-path="the-randomized-trial-as-the-benchmark.html"><a href="the-randomized-trial-as-the-benchmark.html#why-randomization-works"><i class="fa fa-check"></i><b>4.1</b> Why randomization works</a></li>
<li class="chapter" data-level="4.2" data-path="the-randomized-trial-as-the-benchmark.html"><a href="the-randomized-trial-as-the-benchmark.html#intention-to-treat-and-per-protocol"><i class="fa fa-check"></i><b>4.2</b> Intention-to-treat and per-protocol</a></li>
<li class="chapter" data-level="4.3" data-path="the-randomized-trial-as-the-benchmark.html"><a href="the-randomized-trial-as-the-benchmark.html#the-target-trial"><i class="fa fa-check"></i><b>4.3</b> The target trial</a></li>
<li class="chapter" data-level="4.4" data-path="the-randomized-trial-as-the-benchmark.html"><a href="the-randomized-trial-as-the-benchmark.html#exercises-2"><i class="fa fa-check"></i><b>4.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="causal-diagrams.html"><a href="causal-diagrams.html"><i class="fa fa-check"></i><b>5</b> Causal diagrams</a>
<ul>
<li class="chapter" data-level="5.1" data-path="causal-diagrams.html"><a href="causal-diagrams.html#drawing-causal-assumptions"><i class="fa fa-check"></i><b>5.1</b> Drawing causal assumptions</a></li>
<li class="chapter" data-level="5.2" data-path="causal-diagrams.html"><a href="causal-diagrams.html#the-nsaidpud-diagram"><i class="fa fa-check"></i><b>5.2</b> The NSAID–PUD diagram</a></li>
<li class="chapter" data-level="5.3" data-path="causal-diagrams.html"><a href="causal-diagrams.html#confounders-colliders-and-mediators"><i class="fa fa-check"></i><b>5.3</b> Confounders, colliders, and mediators</a></li>
<li class="chapter" data-level="5.4" data-path="causal-diagrams.html"><a href="causal-diagrams.html#selection-bias-as-collider-stratification"><i class="fa fa-check"></i><b>5.4</b> Selection bias as collider stratification</a></li>
<li class="chapter" data-level="5.5" data-path="causal-diagrams.html"><a href="causal-diagrams.html#exercises-3"><i class="fa fa-check"></i><b>5.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="study-design-for-causal-questions.html"><a href="study-design-for-causal-questions.html"><i class="fa fa-check"></i><b>6</b> Study design for causal questions</a>
<ul>
<li class="chapter" data-level="6.1" data-path="study-design-for-causal-questions.html"><a href="study-design-for-causal-questions.html#design-before-analysis"><i class="fa fa-check"></i><b>6.1</b> Design before analysis</a></li>
<li class="chapter" data-level="6.2" data-path="study-design-for-causal-questions.html"><a href="study-design-for-causal-questions.html#new-user-designs"><i class="fa fa-check"></i><b>6.2</b> New-user designs</a></li>
<li class="chapter" data-level="6.3" data-path="study-design-for-causal-questions.html"><a href="study-design-for-causal-questions.html#active-comparator-designs"><i class="fa fa-check"></i><b>6.3</b> Active-comparator designs</a></li>
<li class="chapter" data-level="6.4" data-path="study-design-for-causal-questions.html"><a href="study-design-for-causal-questions.html#immortal-time-and-other-time-zero-problems"><i class="fa fa-check"></i><b>6.4</b> Immortal time and other time-zero problems</a></li>
<li class="chapter" data-level="6.5" data-path="study-design-for-causal-questions.html"><a href="study-design-for-causal-questions.html#exercises-4"><i class="fa fa-check"></i><b>6.5</b> Exercises</a></li>
</ul></li>
<li class="part"><span><b>II Core Methods</b></span></li>
<li class="chapter" data-level="7" data-path="outcome-regression-and-standardization.html"><a href="outcome-regression-and-standardization.html"><i class="fa fa-check"></i><b>7</b> Outcome regression and standardization</a>
<ul>
<li class="chapter" data-level="7.1" data-path="outcome-regression-and-standardization.html"><a href="outcome-regression-and-standardization.html#adjusting-with-regression"><i class="fa fa-check"></i><b>7.1</b> Adjusting with regression</a></li>
<li class="chapter" data-level="7.2" data-path="outcome-regression-and-standardization.html"><a href="outcome-regression-and-standardization.html#standardization-predict-then-average"><i class="fa fa-check"></i><b>7.2</b> Standardization: predict, then average</a></li>
<li class="chapter" data-level="7.3" data-path="outcome-regression-and-standardization.html"><a href="outcome-regression-and-standardization.html#the-bootstrap"><i class="fa fa-check"></i><b>7.3</b> The bootstrap</a></li>
<li class="chapter" data-level="7.4" data-path="outcome-regression-and-standardization.html"><a href="outcome-regression-and-standardization.html#effect-modification"><i class="fa fa-check"></i><b>7.4</b> Effect modification</a></li>
<li class="chapter" data-level="7.5" data-path="outcome-regression-and-standardization.html"><a href="outcome-regression-and-standardization.html#exercises-5"><i class="fa fa-check"></i><b>7.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="propensity-scores.html"><a href="propensity-scores.html"><i class="fa fa-check"></i><b>8</b> Propensity scores</a>
<ul>
<li class="chapter" data-level="8.1" data-path="propensity-scores.html"><a href="propensity-scores.html#one-number-that-summarizes-confounding"><i class="fa fa-check"></i><b>8.1</b> One number that summarizes confounding</a></li>
<li class="chapter" data-level="8.2" data-path="propensity-scores.html"><a href="propensity-scores.html#estimating-the-score"><i class="fa fa-check"></i><b>8.2</b> Estimating the score</a></li>
<li class="chapter" data-level="8.3" data-path="propensity-scores.html"><a href="propensity-scores.html#stratification"><i class="fa fa-check"></i><b>8.3</b> Stratification</a></li>
<li class="chapter" data-level="8.4" data-path="propensity-scores.html"><a href="propensity-scores.html#matching"><i class="fa fa-check"></i><b>8.4</b> Matching</a></li>
<li class="chapter" data-level="8.5" data-path="propensity-scores.html"><a href="propensity-scores.html#choosing-the-ps-model"><i class="fa fa-check"></i><b>8.5</b> Choosing the PS model</a></li>
<li class="chapter" data-level="8.6" data-path="propensity-scores.html"><a href="propensity-scores.html#exercises-6"><i class="fa fa-check"></i><b>8.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html"><i class="fa fa-check"></i><b>9</b> Inverse probability of treatment weighting</a>
<ul>
<li class="chapter" data-level="9.1" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#reweighting-to-a-pseudo-population"><i class="fa fa-check"></i><b>9.1</b> Reweighting to a pseudo-population</a></li>
<li class="chapter" data-level="9.2" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#building-the-weights"><i class="fa fa-check"></i><b>9.2</b> Building the weights</a></li>
<li class="chapter" data-level="9.3" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#estimating-the-effect"><i class="fa fa-check"></i><b>9.3</b> Estimating the effect</a></li>
<li class="chapter" data-level="9.4" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#truncation-and-diagnostics"><i class="fa fa-check"></i><b>9.4</b> Truncation and diagnostics</a></li>
<li class="chapter" data-level="9.5" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#standardized-mortality-ratio-weights"><i class="fa fa-check"></i><b>9.5</b> Standardized mortality ratio weights</a></li>
<li class="chapter" data-level="9.6" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#msms-and-where-weighting-shines"><i class="fa fa-check"></i><b>9.6</b> MSMs and where weighting shines</a></li>
<li class="chapter" data-level="9.7" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#three-estimators-one-estimand"><i class="fa fa-check"></i><b>9.7</b> Three estimators, one estimand</a></li>
<li class="chapter" data-level="9.8" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#exercises-7"><i class="fa fa-check"></i><b>9.8</b> Exercises</a></li>
</ul></li>
<li class="part"><span><b>III Time, Censoring, and Survival</b></span></li>
<li class="chapter" data-level="10" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html"><i class="fa fa-check"></i><b>10</b> Survival outcomes and censoring</a>
<ul>
<li class="chapter" data-level="10.1" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html#the-statin-question"><i class="fa fa-check"></i><b>10.1</b> The statin question</a></li>
<li class="chapter" data-level="10.2" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html#anatomy-of-time-to-event-data"><i class="fa fa-check"></i><b>10.2</b> Anatomy of time-to-event data</a></li>
<li class="chapter" data-level="10.3" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html#kaplanmeier"><i class="fa fa-check"></i><b>10.3</b> Kaplan–Meier</a></li>
<li class="chapter" data-level="10.4" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html#death-as-a-competing-risk"><i class="fa fa-check"></i><b>10.4</b> Death as a competing risk</a></li>
<li class="chapter" data-level="10.5" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html#risks-versus-hazards"><i class="fa fa-check"></i><b>10.5</b> Risks versus hazards</a></li>
<li class="chapter" data-level="10.6" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html#when-censoring-lies"><i class="fa fa-check"></i><b>10.6</b> When censoring lies</a></li>
<li class="chapter" data-level="10.7" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html#exercises-8"><i class="fa fa-check"></i><b>10.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="inverse-probability-of-censoring-weights.html"><a href="inverse-probability-of-censoring-weights.html"><i class="fa fa-check"></i><b>11</b> Inverse probability of censoring weights</a>
<ul>
<li class="chapter" data-level="11.1" data-path="inverse-probability-of-censoring-weights.html"><a href="inverse-probability-of-censoring-weights.html#weighting-returns"><i class="fa fa-check"></i><b>11.1</b> Weighting returns</a></li>
<li class="chapter" data-level="11.2" data-path="inverse-probability-of-censoring-weights.html"><a href="inverse-probability-of-censoring-weights.html#person-period-data"><i class="fa fa-check"></i><b>11.2</b> Person-period data</a></li>
<li class="chapter" data-level="11.3" data-path="inverse-probability-of-censoring-weights.html"><a href="inverse-probability-of-censoring-weights.html#building-censoring-weights"><i class="fa fa-check"></i><b>11.3</b> Building censoring weights</a></li>
<li class="chapter" data-level="11.4" data-path="inverse-probability-of-censoring-weights.html"><a href="inverse-probability-of-censoring-weights.html#weight-diagnostics"><i class="fa fa-check"></i><b>11.4</b> Weight diagnostics</a></li>
<li class="chapter" data-level="11.5" data-path="inverse-probability-of-censoring-weights.html"><a href="inverse-probability-of-censoring-weights.html#did-it-matter"><i class="fa fa-check"></i><b>11.5</b> Did it matter?</a></li>
<li class="chapter" data-level="11.6" data-path="inverse-probability-of-censoring-weights.html"><a href="inverse-probability-of-censoring-weights.html#exercises-9"><i class="fa fa-check"></i><b>11.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="clone-censor-weight.html"><a href="clone-censor-weight.html"><i class="fa fa-check"></i><b>12</b> Clone-censor-weight</a>
<ul>
<li class="chapter" data-level="12.1" data-path="clone-censor-weight.html"><a href="clone-censor-weight.html#from-point-treatments-to-treatment-strategies"><i class="fa fa-check"></i><b>12.1</b> From point treatments to treatment strategies</a></li>
<li class="chapter" data-level="12.2" data-path="clone-censor-weight.html"><a href="clone-censor-weight.html#the-clone-censor-weight-recipe"><i class="fa fa-check"></i><b>12.2</b> The clone-censor-weight recipe</a></li>
<li class="chapter" data-level="12.3" data-path="clone-censor-weight.html"><a href="clone-censor-weight.html#deviation-in-the-statin-cohort"><i class="fa fa-check"></i><b>12.3</b> Deviation in the statin cohort</a></li>
<li class="chapter" data-level="12.4" data-path="clone-censor-weight.html"><a href="clone-censor-weight.html#estimating-per-protocol-risk-curves"><i class="fa fa-check"></i><b>12.4</b> Estimating per-protocol risk curves</a></li>
<li class="chapter" data-level="12.5" data-path="clone-censor-weight.html"><a href="clone-censor-weight.html#interpreting-the-per-protocol-effect"><i class="fa fa-check"></i><b>12.5</b> Interpreting the per-protocol effect</a></li>
<li class="chapter" data-level="12.6" data-path="clone-censor-weight.html"><a href="clone-censor-weight.html#exercises-10"><i class="fa fa-check"></i><b>12.6</b> Exercises</a></li>
</ul></li>
<li class="part"><span><b>IV Beyond Exchangeability</b></span></li>
<li class="chapter" data-level="13" data-path="instrumental-variables.html"><a href="instrumental-variables.html"><i class="fa fa-check"></i><b>13</b> Instrumental variables</a>
<ul>
<li class="chapter" data-level="13.1" data-path="instrumental-variables.html"><a href="instrumental-variables.html#when-exchangeability-fails"><i class="fa fa-check"></i><b>13.1</b> When exchangeability fails</a></li>
<li class="chapter" data-level="13.2" data-path="instrumental-variables.html"><a href="instrumental-variables.html#provider-preference-as-an-instrument"><i class="fa fa-check"></i><b>13.2</b> Provider preference as an instrument</a></li>
<li class="chapter" data-level="13.3" data-path="instrumental-variables.html"><a href="instrumental-variables.html#the-wald-and-two-stage-estimators"><i class="fa fa-check"></i><b>13.3</b> The Wald and two-stage estimators</a></li>
<li class="chapter" data-level="13.4" data-path="instrumental-variables.html"><a href="instrumental-variables.html#interpreting-the-late"><i class="fa fa-check"></i><b>13.4</b> Interpreting the LATE</a></li>
<li class="chapter" data-level="13.5" data-path="instrumental-variables.html"><a href="instrumental-variables.html#exercises-11"><i class="fa fa-check"></i><b>13.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="sensitivity-analysis.html"><a href="sensitivity-analysis.html"><i class="fa fa-check"></i><b>14</b> Sensitivity analysis</a>
<ul>
<li class="chapter" data-level="14.1" data-path="sensitivity-analysis.html"><a href="sensitivity-analysis.html#what-we-assumed-and-cannot-check"><i class="fa fa-check"></i><b>14.1</b> What we assumed and cannot check</a></li>
<li class="chapter" data-level="14.2" data-path="sensitivity-analysis.html"><a href="sensitivity-analysis.html#external-adjustment"><i class="fa fa-check"></i><b>14.2</b> External adjustment</a></li>
<li class="chapter" data-level="14.3" data-path="sensitivity-analysis.html"><a href="sensitivity-analysis.html#the-e-value"><i class="fa fa-check"></i><b>14.3</b> The E-value</a></li>
<li class="chapter" data-level="14.4" data-path="sensitivity-analysis.html"><a href="sensitivity-analysis.html#negative-control-outcomes"><i class="fa fa-check"></i><b>14.4</b> Negative control outcomes</a></li>
<li class="chapter" data-level="14.5" data-path="sensitivity-analysis.html"><a href="sensitivity-analysis.html#reporting-a-causal-analysis"><i class="fa fa-check"></i><b>14.5</b> Reporting a causal analysis</a></li>
<li class="chapter" data-level="14.6" data-path="sensitivity-analysis.html"><a href="sensitivity-analysis.html#exercises-12"><i class="fa fa-check"></i><b>14.6</b> Exercises</a></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="r-and-rstudio-setup.html"><a href="r-and-rstudio-setup.html"><i class="fa fa-check"></i><b>A</b> R and RStudio setup</a>
<ul>
<li class="chapter" data-level="A.1" data-path="r-and-rstudio-setup.html"><a href="r-and-rstudio-setup.html#installing-r-and-rstudio"><i class="fa fa-check"></i><b>A.1</b> Installing R and RStudio</a></li>
<li class="chapter" data-level="A.2" data-path="r-and-rstudio-setup.html"><a href="r-and-rstudio-setup.html#installing-the-packages-this-book-uses"><i class="fa fa-check"></i><b>A.2</b> Installing the packages this book uses</a></li>
<li class="chapter" data-level="A.3" data-path="r-and-rstudio-setup.html"><a href="r-and-rstudio-setup.html#installing-the-namcs-teaching-package"><i class="fa fa-check"></i><b>A.3</b> Installing the NAMCS teaching package</a></li>
<li class="chapter" data-level="A.4" data-path="r-and-rstudio-setup.html"><a href="r-and-rstudio-setup.html#loading-everything-a-chapter-needs"><i class="fa fa-check"></i><b>A.4</b> Loading everything a chapter needs</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="namcs-codebook.html"><a href="namcs-codebook.html"><i class="fa fa-check"></i><b>B</b> NAMCS codebook</a>
<ul>
<li class="chapter" data-level="B.1" data-path="namcs-codebook.html"><a href="namcs-codebook.html#the-nsaid-cohort-ns"><i class="fa fa-check"></i><b>B.1</b> The NSAID cohort (<code>ns</code>)</a></li>
<li class="chapter" data-level="B.2" data-path="namcs-codebook.html"><a href="namcs-codebook.html#the-statin-cohort-sta"><i class="fa fa-check"></i><b>B.2</b> The statin cohort (<code>sta</code>)</a></li>
<li class="chapter" data-level="B.3" data-path="namcs-codebook.html"><a href="namcs-codebook.html#a-note-on-the-outcomes"><i class="fa fa-check"></i><b>B.3</b> A note on the outcomes</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="the-estimator-toolkit.html"><a href="the-estimator-toolkit.html"><i class="fa fa-check"></i><b>C</b> The estimator toolkit</a></li>
<li class="chapter" data-level="D" data-path="course-map-phs-921.html"><a href="course-map-phs-921.html"><i class="fa fa-check"></i><b>D</b> Course map: PHS 921</a></li>
<li class="chapter" data-level="E" data-path="further-reading.html"><a href="further-reading.html"><i class="fa fa-check"></i><b>E</b> Further reading</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Causal Inference in Epidemiology Using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="inverse-probability-of-treatment-weighting" class="section level1 hasAnchor" number="9">
<h1><span class="header-section-number">Chapter 9</span> Inverse probability of treatment weighting<a href="inverse-probability-of-treatment-weighting.html#inverse-probability-of-treatment-weighting" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Chapter 8 built a propensity score and used it in two ways, each of
which discarded information: stratification coarsened the score into
five bands, and matching dropped every nonselective initiator who failed
to pair with a Cox-2 patient. This chapter puts the same fitted score to
a third use that retains every patient. Although the earlier estimators
worked by grouping people who resemble each other, here we leave the
cohort intact and assign each patient a <em>weight</em>, larger for
those who received the treatment their covariates made unlikely and
smaller for those who received the expected one. In the reweighted cohort
treatment and covariates are unrelated by construction, so a comparison
of two weighted means estimates the causal contrast. This is <strong>inverse
probability of treatment weighting</strong>, the last of Part II’s three
estimators and the one that generalizes most readily, since it extends
cleanly to treatments that change over time.</p>
<div id="reweighting-to-a-pseudo-population" class="section level2 hasAnchor" number="9.1">
<h2><span class="header-section-number">9.1</span> Reweighting to a pseudo-population<a href="inverse-probability-of-treatment-weighting.html#reweighting-to-a-pseudo-population" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The intuition is easiest to see in a cohort small enough to work by
hand. Suppose the only confounder is frailty, present in 400 of 1,000
patients. Frail patients are treated with probability 0.60 and
non-frail patients with probability 0.15, and the true risk of the
outcome is 20% in frail patients and 10% in non-frail patients
regardless of treatment — so the treatment does nothing at all.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="inverse-probability-of-treatment-weighting.html#cb66-1" tabindex="-1"></a>toy <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb66-2"><a href="inverse-probability-of-treatment-weighting.html#cb66-2" tabindex="-1"></a>  <span class="at">frail =</span> <span class="fu">c</span>(  <span class="dv">1</span>,   <span class="dv">1</span>,   <span class="dv">0</span>,   <span class="dv">0</span>),</span>
<span id="cb66-3"><a href="inverse-probability-of-treatment-weighting.html#cb66-3" tabindex="-1"></a>  <span class="at">arm   =</span> <span class="fu">c</span>(  <span class="dv">1</span>,   <span class="dv">0</span>,   <span class="dv">1</span>,   <span class="dv">0</span>),</span>
<span id="cb66-4"><a href="inverse-probability-of-treatment-weighting.html#cb66-4" tabindex="-1"></a>  <span class="at">n     =</span> <span class="fu">c</span>(<span class="dv">240</span>, <span class="dv">160</span>,  <span class="dv">90</span>, <span class="dv">510</span>),</span>
<span id="cb66-5"><a href="inverse-probability-of-treatment-weighting.html#cb66-5" tabindex="-1"></a>  <span class="at">cases =</span> <span class="fu">c</span>( <span class="dv">48</span>,  <span class="dv">32</span>,   <span class="dv">9</span>,  <span class="dv">51</span>)</span>
<span id="cb66-6"><a href="inverse-probability-of-treatment-weighting.html#cb66-6" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb66-7"><a href="inverse-probability-of-treatment-weighting.html#cb66-7" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb66-8"><a href="inverse-probability-of-treatment-weighting.html#cb66-8" tabindex="-1"></a>    <span class="at">e        =</span> <span class="fu">if_else</span>(frail <span class="sc">==</span> <span class="dv">1</span>, <span class="fl">0.60</span>, <span class="fl">0.15</span>),</span>
<span id="cb66-9"><a href="inverse-probability-of-treatment-weighting.html#cb66-9" tabindex="-1"></a>    <span class="at">wt       =</span> <span class="fu">if_else</span>(arm <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1</span> <span class="sc">/</span> e, <span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> e)),</span>
<span id="cb66-10"><a href="inverse-probability-of-treatment-weighting.html#cb66-10" tabindex="-1"></a>    <span class="at">pseudo_n =</span> n <span class="sc">*</span> wt,</span>
<span id="cb66-11"><a href="inverse-probability-of-treatment-weighting.html#cb66-11" tabindex="-1"></a>    <span class="at">pseudo_y =</span> cases <span class="sc">*</span> wt</span>
<span id="cb66-12"><a href="inverse-probability-of-treatment-weighting.html#cb66-12" tabindex="-1"></a>  )</span>
<span id="cb66-13"><a href="inverse-probability-of-treatment-weighting.html#cb66-13" tabindex="-1"></a></span>
<span id="cb66-14"><a href="inverse-probability-of-treatment-weighting.html#cb66-14" tabindex="-1"></a>toy <span class="sc">|&gt;</span> knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">frail</th>
<th align="right">arm</th>
<th align="right">n</th>
<th align="right">cases</th>
<th align="right">e</th>
<th align="right">wt</th>
<th align="right">pseudo_n</th>
<th align="right">pseudo_y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">1</td>
<td align="right">240</td>
<td align="right">48</td>
<td align="right">0.60</td>
<td align="right">1.667</td>
<td align="right">400</td>
<td align="right">80</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="right">0</td>
<td align="right">160</td>
<td align="right">32</td>
<td align="right">0.60</td>
<td align="right">2.500</td>
<td align="right">400</td>
<td align="right">80</td>
</tr>
<tr class="odd">
<td align="right">0</td>
<td align="right">1</td>
<td align="right">90</td>
<td align="right">9</td>
<td align="right">0.15</td>
<td align="right">6.667</td>
<td align="right">600</td>
<td align="right">60</td>
</tr>
<tr class="even">
<td align="right">0</td>
<td align="right">0</td>
<td align="right">510</td>
<td align="right">51</td>
<td align="right">0.15</td>
<td align="right">1.176</td>
<td align="right">600</td>
<td align="right">60</td>
</tr>
</tbody>
</table>
<p>Compared crudely, treatment looks harmful: risk
17.3% among the treated against
12.4% among the untreated, a risk
difference of
+4.9 percentage
points for a drug with no effect. The reason is entirely in the <code>n</code>
column: the treated arm is nearly three-quarters frail, the untreated
arm three-quarters not.</p>
<p>Now read the <code>wt</code> column. A frail treated patient had probability 0.60
of ending up where she did, so she stands in for <span class="math inline">\(1/0.60 = 1.67\)</span>
patients like her; a frail <em>untreated</em> patient had probability 0.40, so
she stands in for two and a half. Look at <code>pseudo_n</code>: both arms now
contain 400 frail and 600 non-frail patients, 1,000 apiece — each arm
inflated into a copy of the whole cohort. In this
<strong>pseudo-population</strong> — Hernán and Robins’s term for the reweighted
cohort — frailty is distributed identically across arms; the association
between frailty and treatment has been broken by duplicating patients
rather than by conditioning on frailty, and the weighted risks come out at
14.0% and
14.0%, a risk difference of exactly
zero.</p>
<p>That is the essential idea, and the general form of the weight follows
directly. For a patient with covariates <span class="math inline">\(L\)</span> who received treatment <span class="math inline">\(A\)</span>
the weight is</p>
<p><span class="math display">\[W = \frac{1}{P(A \mid L)} = \frac{A}{e(L)} + \frac{1-A}{1 - e(L)},\]</span></p>
<p>the reciprocal of the probability of the treatment actually received,
which is where the estimator’s name comes from. Each patient represents
herself plus everyone with her covariates who <em>would</em> have gone the
other way, and Chapter 3’s identification conditions license that
substitution: consistency, conditional exchangeability given <span class="math inline">\(L\)</span>, and
positivity. Positivity is doing conspicuous work here, because as <span class="math inline">\(e(L)\)</span>
approaches zero for a treated patient her weight grows without bound, and
a handful of patients can come to speak for the entire pseudo-population.</p>
</div>
<div id="building-the-weights" class="section level2 hasAnchor" number="9.2">
<h2><span class="header-section-number">9.2</span> Building the weights<a href="inverse-probability-of-treatment-weighting.html#building-the-weights" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The weight above, <span class="math inline">\(1/P(A \mid L)\)</span>, is the <strong>unstabilized</strong> weight. It
averages to about 2, because each arm is inflated to the size of the
full cohort and the pseudo-population is therefore roughly twice the
real one. Nothing is wrong with that, although it makes the weights
larger and more variable than they need to be, and variability in the
weights inflates the variance of the estimate.</p>
<p><strong>Stabilized</strong> weights fix this by multiplying by the marginal
probability of the treatment received,</p>
<p><span class="math display">\[W^{s} = \frac{P(A)}{P(A \mid L)} = A\,\frac{\Pr(A=1)}{e(L)} + (1-A)\,\frac{1 - \Pr(A=1)}{1 - e(L)}.\]</span></p>
<p>The numerator does not depend on covariates, so it cannot undo the
balancing the denominator achieves; it does no more than rescale each arm so that
the pseudo-population is about the size of the real cohort. The
diagnostic consequence is convenient: stabilized weights should average
close to 1, and a mean far from 1 is a sign that the treatment model is
misbehaving. Cole and Hernán (2008) are the practical reference for
constructing these weights and for reading their mean this way.</p>
<p>Our estimator packages the whole procedure — fit the treatment model,
form the weights, optionally truncate them, and fit a weighted
regression of the outcome on treatment alone.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="inverse-probability-of-treatment-weighting.html#cb67-1" tabindex="-1"></a>iptw_estimator <span class="ot">&lt;-</span> <span class="cf">function</span>(data, treat_model, outcome, treat,</span>
<span id="cb67-2"><a href="inverse-probability-of-treatment-weighting.html#cb67-2" tabindex="-1"></a>                           <span class="at">family =</span> <span class="fu">gaussian</span>(), <span class="at">stabilize =</span> <span class="cn">TRUE</span>,</span>
<span id="cb67-3"><a href="inverse-probability-of-treatment-weighting.html#cb67-3" tabindex="-1"></a>                           <span class="at">truncate_at =</span> <span class="cn">NULL</span>) {</span>
<span id="cb67-4"><a href="inverse-probability-of-treatment-weighting.html#cb67-4" tabindex="-1"></a>  data <span class="ot">&lt;-</span> <span class="fu">est_ps</span>(data, treat_model)</span>
<span id="cb67-5"><a href="inverse-probability-of-treatment-weighting.html#cb67-5" tabindex="-1"></a>  p_treat <span class="ot">&lt;-</span> <span class="fu">mean</span>(data[[treat]])</span>
<span id="cb67-6"><a href="inverse-probability-of-treatment-weighting.html#cb67-6" tabindex="-1"></a></span>
<span id="cb67-7"><a href="inverse-probability-of-treatment-weighting.html#cb67-7" tabindex="-1"></a>  data <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb67-8"><a href="inverse-probability-of-treatment-weighting.html#cb67-8" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb67-9"><a href="inverse-probability-of-treatment-weighting.html#cb67-9" tabindex="-1"></a>      <span class="at">wt =</span> <span class="fu">if_else</span>(.data[[treat]] <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1</span> <span class="sc">/</span> ps, <span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> ps)),</span>
<span id="cb67-10"><a href="inverse-probability-of-treatment-weighting.html#cb67-10" tabindex="-1"></a>      <span class="at">wt =</span> <span class="cf">if</span> (stabilize) {</span>
<span id="cb67-11"><a href="inverse-probability-of-treatment-weighting.html#cb67-11" tabindex="-1"></a>        <span class="fu">if_else</span>(.data[[treat]] <span class="sc">==</span> <span class="dv">1</span>, p_treat <span class="sc">*</span> wt, (<span class="dv">1</span> <span class="sc">-</span> p_treat) <span class="sc">*</span> wt)</span>
<span id="cb67-12"><a href="inverse-probability-of-treatment-weighting.html#cb67-12" tabindex="-1"></a>      } <span class="cf">else</span> wt</span>
<span id="cb67-13"><a href="inverse-probability-of-treatment-weighting.html#cb67-13" tabindex="-1"></a>    )</span>
<span id="cb67-14"><a href="inverse-probability-of-treatment-weighting.html#cb67-14" tabindex="-1"></a></span>
<span id="cb67-15"><a href="inverse-probability-of-treatment-weighting.html#cb67-15" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(truncate_at)) {</span>
<span id="cb67-16"><a href="inverse-probability-of-treatment-weighting.html#cb67-16" tabindex="-1"></a>    data <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">wt =</span> <span class="fu">pmin</span>(wt, <span class="fu">quantile</span>(wt, truncate_at)))</span>
<span id="cb67-17"><a href="inverse-probability-of-treatment-weighting.html#cb67-17" tabindex="-1"></a>  }</span>
<span id="cb67-18"><a href="inverse-probability-of-treatment-weighting.html#cb67-18" tabindex="-1"></a></span>
<span id="cb67-19"><a href="inverse-probability-of-treatment-weighting.html#cb67-19" tabindex="-1"></a>  fit <span class="ot">&lt;-</span> geepack<span class="sc">::</span><span class="fu">geeglm</span>(</span>
<span id="cb67-20"><a href="inverse-probability-of-treatment-weighting.html#cb67-20" tabindex="-1"></a>    <span class="fu">reformulate</span>(treat, outcome),</span>
<span id="cb67-21"><a href="inverse-probability-of-treatment-weighting.html#cb67-21" tabindex="-1"></a>    <span class="at">id =</span> <span class="fu">seq_len</span>(<span class="fu">nrow</span>(data)), <span class="at">weights =</span> data<span class="sc">$</span>wt,</span>
<span id="cb67-22"><a href="inverse-probability-of-treatment-weighting.html#cb67-22" tabindex="-1"></a>    <span class="at">family =</span> family, <span class="at">data =</span> data</span>
<span id="cb67-23"><a href="inverse-probability-of-treatment-weighting.html#cb67-23" tabindex="-1"></a>  )</span>
<span id="cb67-24"><a href="inverse-probability-of-treatment-weighting.html#cb67-24" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>(fit, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span>
<span id="cb67-25"><a href="inverse-probability-of-treatment-weighting.html#cb67-25" tabindex="-1"></a>}</span></code></pre></div>
<p>Three details deserve comment. The function calls Chapter 8’s <code>est_ps()</code>
rather than fitting its own logistic model, which keeps one definition of
“propensity score” in the book. The outcome regression is
<code>reformulate(treat, outcome)</code> — treatment and nothing else, because the
weights have already dealt with the covariates; a weighted regression
that also adjusted for <code>ns_covs</code> would be a different, doubly adjusted
estimator. And the fit goes through <code>geepack::geeglm()</code> with
<code>id = seq_len(nrow(data))</code>, making every patient her own cluster under an
independent working correlation. That is an elaborate way to reproduce a
<code>glm()</code> point estimate, but it delivers the sandwich standard error,
which is what we need here. A weighted <code>glm()</code> treats the weights as
counts of real observations and reports intervals that are far too
narrow, whereas the robust variance from <code>geeglm()</code> is estimated
empirically rather than from the weighted likelihood.</p>
<p>That code lives in <code>R/iptw_estimator.R</code>. Before using it, we look at the
weights themselves.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="inverse-probability-of-treatment-weighting.html#cb68-1" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;R/propensity.R&quot;</span>)</span>
<span id="cb68-2"><a href="inverse-probability-of-treatment-weighting.html#cb68-2" tabindex="-1"></a></span>
<span id="cb68-3"><a href="inverse-probability-of-treatment-weighting.html#cb68-3" tabindex="-1"></a>ps_model <span class="ot">&lt;-</span> <span class="fu">reformulate</span>(ns_covs, <span class="st">&quot;cox2_init&quot;</span>)</span>
<span id="cb68-4"><a href="inverse-probability-of-treatment-weighting.html#cb68-4" tabindex="-1"></a>wts <span class="ot">&lt;-</span> <span class="fu">est_ps</span>(ns, ps_model) <span class="sc">|&gt;</span></span>
<span id="cb68-5"><a href="inverse-probability-of-treatment-weighting.html#cb68-5" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb68-6"><a href="inverse-probability-of-treatment-weighting.html#cb68-6" tabindex="-1"></a>    <span class="at">p_treat  =</span> <span class="fu">mean</span>(cox2_init),</span>
<span id="cb68-7"><a href="inverse-probability-of-treatment-weighting.html#cb68-7" tabindex="-1"></a>    <span class="at">w_unstab =</span> <span class="fu">if_else</span>(cox2_init <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1</span> <span class="sc">/</span> ps, <span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> ps)),</span>
<span id="cb68-8"><a href="inverse-probability-of-treatment-weighting.html#cb68-8" tabindex="-1"></a>    <span class="at">w_stab   =</span> <span class="fu">if_else</span>(cox2_init <span class="sc">==</span> <span class="dv">1</span>, p_treat <span class="sc">*</span> w_unstab,</span>
<span id="cb68-9"><a href="inverse-probability-of-treatment-weighting.html#cb68-9" tabindex="-1"></a>                       (<span class="dv">1</span> <span class="sc">-</span> p_treat) <span class="sc">*</span> w_unstab)</span>
<span id="cb68-10"><a href="inverse-probability-of-treatment-weighting.html#cb68-10" tabindex="-1"></a>  )</span>
<span id="cb68-11"><a href="inverse-probability-of-treatment-weighting.html#cb68-11" tabindex="-1"></a></span>
<span id="cb68-12"><a href="inverse-probability-of-treatment-weighting.html#cb68-12" tabindex="-1"></a><span class="fu">summary</span>(wts<span class="sc">$</span>w_unstab)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.017   1.053   1.079   1.955   1.130  34.182</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="inverse-probability-of-treatment-weighting.html#cb70-1" tabindex="-1"></a><span class="fu">summary</span>(wts<span class="sc">$</span>w_stab)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.1646  0.9605  0.9826  0.9967  1.0212  2.8465</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="inverse-probability-of-treatment-weighting.html#cb72-1" tabindex="-1"></a><span class="fu">ggplot</span>(wts, <span class="fu">aes</span>(<span class="at">x =</span> w_stab)) <span class="sc">+</span></span>
<span id="cb72-2"><a href="inverse-probability-of-treatment-weighting.html#cb72-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">40</span>, <span class="at">fill =</span> <span class="st">&quot;grey35&quot;</span>) <span class="sc">+</span></span>
<span id="cb72-3"><a href="inverse-probability-of-treatment-weighting.html#cb72-3" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(</span>
<span id="cb72-4"><a href="inverse-probability-of-treatment-weighting.html#cb72-4" tabindex="-1"></a>    <span class="sc">~</span> <span class="fu">factor</span>(cox2_init, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Nonselective NSAID&quot;</span>, <span class="st">&quot;Cox-2 selective&quot;</span>)),</span>
<span id="cb72-5"><a href="inverse-probability-of-treatment-weighting.html#cb72-5" tabindex="-1"></a>    <span class="at">scales =</span> <span class="st">&quot;free_y&quot;</span></span>
<span id="cb72-6"><a href="inverse-probability-of-treatment-weighting.html#cb72-6" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb72-7"><a href="inverse-probability-of-treatment-weighting.html#cb72-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Stabilized weight&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Patients&quot;</span>) <span class="sc">+</span></span>
<span id="cb72-8"><a href="inverse-probability-of-treatment-weighting.html#cb72-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="causal-inference-epi-r_files/figure-html/ch09-wt-hist-1.png" alt="" width="672" /></p>
<p>The stabilized weights average 0.997, close
enough to 1 to be reassuring, while the unstabilized ones average about
2 as advertised. The maxima are more informative:
34.2 unstabilized against
2.8 stabilized. That largest unstabilized weight
belongs to the Cox-2 initiator whose estimated propensity score is
0.029 — a patient whose covariates made the
Cox-2 drug very unlikely, who received it anyway, and who is therefore
asked to represent thirty-odd patients like herself who did not. Kish’s
effective sample size, <span class="math inline">\((\sum w)^2 / \sum w^2\)</span>, falls from
2882 unweighted to 2823 under stabilized
weights and all the way to 756 unstabilized: a
compact measure of how much information a few large weights consume.</p>
<p>The histogram shows where the asymmetry lies. Nonselective initiators
are the common case, so their weights cluster tightly around 1, while
the Cox-2 arm spreads out with a long right tail:
38 patients carry a stabilized weight above 1.5, of whom
36 are Cox-2 initiators. Extreme weights are best read as a
symptom of a positivity problem rather than as a numerical nuisance to be
tidied away. The patient with the largest weight sits in the sparse left
tail of Chapter 8’s density plot, where matching declined to find a
partner. Matching reported that difficulty by leaving her out, whereas
weighting reports it by making her highly influential, which is easier to
miss, so the weight distribution should be printed and plotted routinely.</p>
</div>
<div id="estimating-the-effect" class="section level2 hasAnchor" number="9.3">
<h2><span class="header-section-number">9.3</span> Estimating the effect<a href="inverse-probability-of-treatment-weighting.html#estimating-the-effect" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>With the weights in hand the effect estimate is a weighted regression of
<code>pud</code> on <code>cox2_init</code> and nothing else. The link function chooses the
scale: an identity link on a 0/1 outcome — <code>family = gaussian()</code> — gives
the treatment coefficient as a risk difference, and a log link with
<code>poisson()</code> gives it as a log risk ratio, which we exponentiate.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="inverse-probability-of-treatment-weighting.html#cb73-1" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;R/propensity.R&quot;</span>); <span class="fu">source</span>(<span class="st">&quot;R/iptw_estimator.R&quot;</span>)</span>
<span id="cb73-2"><a href="inverse-probability-of-treatment-weighting.html#cb73-2" tabindex="-1"></a>ps_model <span class="ot">&lt;-</span> <span class="fu">reformulate</span>(ns_covs, <span class="st">&quot;cox2_init&quot;</span>)</span>
<span id="cb73-3"><a href="inverse-probability-of-treatment-weighting.html#cb73-3" tabindex="-1"></a><span class="fu">iptw_estimator</span>(ns, ps_model, <span class="at">outcome =</span> <span class="st">&quot;pud&quot;</span>, <span class="at">treat =</span> <span class="st">&quot;cox2_init&quot;</span>,</span>
<span id="cb73-4"><a href="inverse-probability-of-treatment-weighting.html#cb73-4" tabindex="-1"></a>               <span class="at">family =</span> <span class="fu">gaussian</span>()) <span class="sc">|&gt;</span> knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">4</span>)</span></code></pre></div>
<table>
<colgroup>
<col width="17%" />
<col width="13%" />
<col width="14%" />
<col width="14%" />
<col width="11%" />
<col width="13%" />
<col width="14%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">conf.low</th>
<th align="right">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.1018</td>
<td align="right">0.006</td>
<td align="right">286.7239</td>
<td align="right">0.0000</td>
<td align="right">0.0900</td>
<td align="right">0.1136</td>
</tr>
<tr class="even">
<td align="left">cox2_init</td>
<td align="right">-0.0029</td>
<td align="right">0.020</td>
<td align="right">0.0202</td>
<td align="right">0.8869</td>
<td align="right">-0.0421</td>
<td align="right">0.0364</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="inverse-probability-of-treatment-weighting.html#cb74-1" tabindex="-1"></a><span class="fu">iptw_estimator</span>(ns, ps_model, <span class="at">outcome =</span> <span class="st">&quot;pud&quot;</span>, <span class="at">treat =</span> <span class="st">&quot;cox2_init&quot;</span>,</span>
<span id="cb74-2"><a href="inverse-probability-of-treatment-weighting.html#cb74-2" tabindex="-1"></a>               <span class="at">family =</span> <span class="fu">poisson</span>(<span class="at">link =</span> <span class="st">&quot;log&quot;</span>)) <span class="sc">|&gt;</span></span>
<span id="cb74-3"><a href="inverse-probability-of-treatment-weighting.html#cb74-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(estimate, conf.low, conf.high), exp)) <span class="sc">|&gt;</span> knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code></pre></div>
<table>
<colgroup>
<col width="17%" />
<col width="13%" />
<col width="14%" />
<col width="14%" />
<col width="11%" />
<col width="13%" />
<col width="14%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">conf.low</th>
<th align="right">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.102</td>
<td align="right">0.059</td>
<td align="right">1496.629</td>
<td align="right">0.000</td>
<td align="right">0.091</td>
<td align="right">0.114</td>
</tr>
<tr class="even">
<td align="left">cox2_init</td>
<td align="right">0.972</td>
<td align="right">0.202</td>
<td align="right">0.020</td>
<td align="right">0.888</td>
<td align="right">0.654</td>
<td align="right">1.444</td>
</tr>
</tbody>
</table>
<p>The weighted risk difference is
-0.29 percentage points, with a 95%
interval from -4.2 to
+3.6 points, and the weighted risk ratio
is 0.97
(0.65 to 1.44).
Both estimates sit essentially on the null. The Poisson fit deserves a
note. The outcome is binary rather than a count, so the likelihood is
deliberately wrong, although the coefficient of a log-link regression on
a 0/1 outcome still estimates a log risk ratio, and the sandwich variance
repairs the standard error that the wrong likelihood would give. This is
the modified Poisson approach to risk ratios, and it is a further reason
for the <code>geeglm()</code> machinery.</p>
<p>There is very little on the outcome side of this analysis: the regression
has one covariate. Everything we know about age, arthritis, steroids, and
the other seventeen variables entered through the weights, which were
built without ever looking at <code>pud</code>, so Chapter 8’s design-stage
discipline carries through to the estimate.</p>
</div>
<div id="truncation-and-diagnostics" class="section level2 hasAnchor" number="9.4">
<h2><span class="header-section-number">9.4</span> Truncation and diagnostics<a href="inverse-probability-of-treatment-weighting.html#truncation-and-diagnostics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The obvious response to a weight of 34.2 is to
cap it. <strong>Truncation</strong> replaces every weight above a chosen percentile
with the value at that percentile; our function does this with
<code>pmin(wt, quantile(wt, truncate_at))</code> when <code>truncate_at</code> is supplied.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="inverse-probability-of-treatment-weighting.html#cb75-1" tabindex="-1"></a><span class="fu">iptw_estimator</span>(ns, ps_model, <span class="at">outcome =</span> <span class="st">&quot;pud&quot;</span>, <span class="at">treat =</span> <span class="st">&quot;cox2_init&quot;</span>,</span>
<span id="cb75-2"><a href="inverse-probability-of-treatment-weighting.html#cb75-2" tabindex="-1"></a>               <span class="at">family =</span> <span class="fu">gaussian</span>(), <span class="at">truncate_at =</span> <span class="fl">0.99</span>) <span class="sc">|&gt;</span></span>
<span id="cb75-3"><a href="inverse-probability-of-treatment-weighting.html#cb75-3" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">4</span>)</span></code></pre></div>
<table>
<colgroup>
<col width="17%" />
<col width="13%" />
<col width="14%" />
<col width="14%" />
<col width="11%" />
<col width="13%" />
<col width="14%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">conf.low</th>
<th align="right">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.1018</td>
<td align="right">0.0060</td>
<td align="right">286.7243</td>
<td align="right">0.0000</td>
<td align="right">0.0900</td>
<td align="right">0.1136</td>
</tr>
<tr class="even">
<td align="left">cox2_init</td>
<td align="right">-0.0002</td>
<td align="right">0.0202</td>
<td align="right">0.0002</td>
<td align="right">0.9902</td>
<td align="right">-0.0398</td>
<td align="right">0.0393</td>
</tr>
</tbody>
</table>
<p>Capping at the 99th percentile touches 29 of the
2882 patients and moves the risk difference from
-0.29 to
-0.02 percentage points, with the standard
error changing from 0.0200 to
0.0202. Truncation therefore buys almost nothing in
this cohort, which is itself informative: the estimate is robust to the
handful of most influential patients.</p>
<p>The trade-off deserves to be stated explicitly, since truncation is a
deliberate exchange of bias for variance. If the treatment model is
correct, the untruncated estimator is consistent for the ATE and the
truncated one is not, because we have knowingly misrepresented how much
of the pseudo-population the extreme patients should represent. What we
get in return is stability, and when a single weight dominates the sum a
small amount of bias can be worth accepting. Truncation is therefore
better used as a sensitivity analysis than as a default: report the
untruncated estimate, report it capped at the 99th and 95th percentiles,
and if they disagree materially, say so. An estimate that depends on
whether one patient counts thirty times or ten is being driven by
extrapolation into a region where the data are thin, and no choice of cap
will remedy that.
Trimming, which drops patients outside a range of the propensity score
altogether, is the other common option; it changes the population and
therefore the estimand, and should be described as such. The distinction
is worth holding onto, since the two words are not always kept apart:
truncation caps a weight and keeps the patient, trimming discards the
patient — often those outside a percentile range of the propensity score
— and both the course and much of the literature use “trimming” loosely
for either operation, so it is worth saying which one you did.</p>
</div>
<div id="standardized-mortality-ratio-weights" class="section level2 hasAnchor" number="9.5">
<h2><span class="header-section-number">9.5</span> Standardized mortality ratio weights<a href="inverse-probability-of-treatment-weighting.html#standardized-mortality-ratio-weights" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The weights built so far blow both arms up into a copy of the whole
cohort, which is why they estimate the ATE. A small change to the weight
redirects the estimator at a different population. Leave the treated arm
alone — every treated patient keeps weight 1 — and give each untreated
patient <span class="math inline">\(e(L) / (1 - e(L))\)</span>, the odds of treatment her covariates imply.
The untreated are then reweighted to resemble the treated rather than the
cohort, the treated covariate distribution becomes the standard, and the
estimand is the ATT: the effect of treatment among the treated. In the
course these are called <strong>SMR (standardized mortality ratio) weights</strong>,
after the indirect standardization that gives a standardized mortality
ratio its name.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="inverse-probability-of-treatment-weighting.html#cb76-1" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;R/propensity.R&quot;</span>)</span>
<span id="cb76-2"><a href="inverse-probability-of-treatment-weighting.html#cb76-2" tabindex="-1"></a></span>
<span id="cb76-3"><a href="inverse-probability-of-treatment-weighting.html#cb76-3" tabindex="-1"></a>smr <span class="ot">&lt;-</span> <span class="fu">est_ps</span>(ns, ps_model) <span class="sc">|&gt;</span></span>
<span id="cb76-4"><a href="inverse-probability-of-treatment-weighting.html#cb76-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">w_smr =</span> <span class="fu">if_else</span>(cox2_init <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1</span>, ps <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> ps)))</span>
<span id="cb76-5"><a href="inverse-probability-of-treatment-weighting.html#cb76-5" tabindex="-1"></a></span>
<span id="cb76-6"><a href="inverse-probability-of-treatment-weighting.html#cb76-6" tabindex="-1"></a>smr_fit <span class="ot">&lt;-</span> geepack<span class="sc">::</span><span class="fu">geeglm</span>(</span>
<span id="cb76-7"><a href="inverse-probability-of-treatment-weighting.html#cb76-7" tabindex="-1"></a>  pud <span class="sc">~</span> cox2_init,</span>
<span id="cb76-8"><a href="inverse-probability-of-treatment-weighting.html#cb76-8" tabindex="-1"></a>  <span class="at">id =</span> <span class="fu">seq_len</span>(<span class="fu">nrow</span>(smr)), <span class="at">weights =</span> smr<span class="sc">$</span>w_smr,</span>
<span id="cb76-9"><a href="inverse-probability-of-treatment-weighting.html#cb76-9" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">gaussian</span>(), <span class="at">data =</span> smr</span>
<span id="cb76-10"><a href="inverse-probability-of-treatment-weighting.html#cb76-10" tabindex="-1"></a>)</span>
<span id="cb76-11"><a href="inverse-probability-of-treatment-weighting.html#cb76-11" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(smr_fit, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">4</span>)</span></code></pre></div>
<table>
<colgroup>
<col width="17%" />
<col width="13%" />
<col width="14%" />
<col width="14%" />
<col width="11%" />
<col width="13%" />
<col width="14%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">conf.low</th>
<th align="right">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.1473</td>
<td align="right">0.0100</td>
<td align="right">218.6235</td>
<td align="right">0.0000</td>
<td align="right">0.1277</td>
<td align="right">0.1668</td>
</tr>
<tr class="even">
<td align="left">cox2_init</td>
<td align="right">-0.0223</td>
<td align="right">0.0236</td>
<td align="right">0.8924</td>
<td align="right">0.3448</td>
<td align="right">-0.0684</td>
<td align="right">0.0239</td>
</tr>
</tbody>
</table>
<p>The SMR-weighted risk difference is
-2.23 percentage points
(-6.8 to
+2.4). Set beside the ATE of
-0.29 points from the same score and
Chapter 8’s matched estimate of -4.18
points on the same cohort, it lands between them. That is unsurprising.
SMR weighting targets the ATT, as matching did, although it reaches the
ATT by retaining the unmatched controls at reduced weight rather than
discarding them, so the two ATT estimates need not coincide, and neither
sits far from the null. The weights themselves indicate what this costs:
among the untreated they average only 0.09 and
none exceeds 0.73, because the common arm has to
be shrunk substantially to resemble the rare one. The confidence interval
widens accordingly, which is the price of asking about the treated rather
than about everyone.</p>
</div>
<div id="msms-and-where-weighting-shines" class="section level2 hasAnchor" number="9.6">
<h2><span class="header-section-number">9.6</span> MSMs and where weighting shines<a href="inverse-probability-of-treatment-weighting.html#msms-and-where-weighting-shines" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The one-covariate regression we fit in the pseudo-population has a name.
A <strong>marginal structural model</strong> is a model for the marginal mean of a
potential outcome as a function of treatment,</p>
<p><span class="math display">\[E[Y(a)] = \beta_0 + \beta_1 a,\]</span></p>
<p><em>structural</em> because its arguments are counterfactual treatments rather
than observed ones, <em>marginal</em> because it averages over the covariate
distribution instead of conditioning on it. The class, and the name, are
Robins, Hernán, and Brumback’s (2000). Under the identification
conditions, fitting it in the weighted data estimates its parameters, so
<span class="math inline">\(\beta_1\)</span> is the ATE of Chapter 3 — the same estimand standardization
targeted, reached by another route. Ours is <em>saturated</em>: with a binary
treatment it has one parameter per arm and so cannot be misspecified.
Larger MSMs can be, and often carry baseline effect modifiers on the
right-hand side to allow subgroup effects.</p>
<p>The more important reason to learn weighting is that the framework
extends to time-varying treatment, whereas conditioning does not.
Suppose patients start and stop a drug over months of follow-up while
their covariates evolve. A confounder measured at month six may itself be
affected by treatment at month three, making it a mediator as well as a
confounder. If we adjust for it in an outcome regression we block part of
the effect we are trying to measure and may induce collider bias as well,
whereas if we leave it out the later treatment remains confounded. No
choice of covariate set resolves that conflict by conditioning, but
weighting can: build a weight from a treatment model at each time point,
multiply the per-visit weights along each patient’s history, and fit a
marginal structural model in the resulting pseudo-population. The
time-varying covariates then appear only in the weight models, where they
cause no trouble, and never in the outcome model, so nothing is blocked.
Chapter 11 applies the same logic to censoring rather than treatment, and
Chapter 12 uses it to emulate trials with sustained strategies; much of
Part III consists of variations on this chapter.</p>
</div>
<div id="three-estimators-one-estimand" class="section level2 hasAnchor" number="9.7">
<h2><span class="header-section-number">9.7</span> Three estimators, one estimand<a href="inverse-probability-of-treatment-weighting.html#three-estimators-one-estimand" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Part II asked one question three times. Here are the answers, with the
crude comparison for reference. The standardization row re-runs
<code>standardize()</code> with Chapter 7’s seed, so its bootstrap interval
reproduces that chapter’s exactly.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="inverse-probability-of-treatment-weighting.html#cb77-1" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;R/standardize.R&quot;</span>)</span>
<span id="cb77-2"><a href="inverse-probability-of-treatment-weighting.html#cb77-2" tabindex="-1"></a></span>
<span id="cb77-3"><a href="inverse-probability-of-treatment-weighting.html#cb77-3" tabindex="-1"></a>crude <span class="ot">&lt;-</span> ns <span class="sc">|&gt;</span></span>
<span id="cb77-4"><a href="inverse-probability-of-treatment-weighting.html#cb77-4" tabindex="-1"></a>  <span class="fu">group_by</span>(cox2_init) <span class="sc">|&gt;</span></span>
<span id="cb77-5"><a href="inverse-probability-of-treatment-weighting.html#cb77-5" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">r =</span> <span class="fu">mean</span>(pud), <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb77-6"><a href="inverse-probability-of-treatment-weighting.html#cb77-6" tabindex="-1"></a>  <span class="fu">pull</span>(r)</span>
<span id="cb77-7"><a href="inverse-probability-of-treatment-weighting.html#cb77-7" tabindex="-1"></a>std <span class="ot">&lt;-</span> <span class="fu">standardize</span>(ns, <span class="fu">reformulate</span>(<span class="fu">c</span>(<span class="st">&quot;cox2_init&quot;</span>, ns_covs), <span class="st">&quot;pud&quot;</span>),</span>
<span id="cb77-8"><a href="inverse-probability-of-treatment-weighting.html#cb77-8" tabindex="-1"></a>                   <span class="at">treat =</span> <span class="st">&quot;cox2_init&quot;</span>, <span class="at">n_boot =</span> <span class="dv">200</span>, <span class="at">seed =</span> <span class="dv">921</span>)</span>
<span id="cb77-9"><a href="inverse-probability-of-treatment-weighting.html#cb77-9" tabindex="-1"></a>ipw <span class="ot">&lt;-</span> <span class="fu">iptw_estimator</span>(ns, ps_model, <span class="at">outcome =</span> <span class="st">&quot;pud&quot;</span>, <span class="at">treat =</span> <span class="st">&quot;cox2_init&quot;</span>)</span>
<span id="cb77-10"><a href="inverse-probability-of-treatment-weighting.html#cb77-10" tabindex="-1"></a></span>
<span id="cb77-11"><a href="inverse-probability-of-treatment-weighting.html#cb77-11" tabindex="-1"></a>pick <span class="ot">&lt;-</span> <span class="cf">function</span>(d, what, col) d[[col]][d[[<span class="dv">1</span>]] <span class="sc">==</span> what]</span>
<span id="cb77-12"><a href="inverse-probability-of-treatment-weighting.html#cb77-12" tabindex="-1"></a></span>
<span id="cb77-13"><a href="inverse-probability-of-treatment-weighting.html#cb77-13" tabindex="-1"></a>comparison <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb77-14"><a href="inverse-probability-of-treatment-weighting.html#cb77-14" tabindex="-1"></a>  <span class="at">estimator =</span> <span class="fu">c</span>(<span class="st">&quot;Crude&quot;</span>, <span class="st">&quot;Standardization (Ch. 7)&quot;</span>, <span class="st">&quot;IPTW, stabilized&quot;</span>),</span>
<span id="cb77-15"><a href="inverse-probability-of-treatment-weighting.html#cb77-15" tabindex="-1"></a>  <span class="at">estimand  =</span> <span class="fu">c</span>(<span class="st">&quot;none (confounded)&quot;</span>, <span class="st">&quot;ATE&quot;</span>, <span class="st">&quot;ATE&quot;</span>),</span>
<span id="cb77-16"><a href="inverse-probability-of-treatment-weighting.html#cb77-16" tabindex="-1"></a>  <span class="at">rd_pp     =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">c</span>(crude[<span class="dv">2</span>] <span class="sc">-</span> crude[<span class="dv">1</span>], <span class="fu">pick</span>(std, <span class="st">&quot;rd&quot;</span>, <span class="st">&quot;estimate&quot;</span>),</span>
<span id="cb77-17"><a href="inverse-probability-of-treatment-weighting.html#cb77-17" tabindex="-1"></a>                      <span class="fu">pick</span>(ipw, <span class="st">&quot;cox2_init&quot;</span>, <span class="st">&quot;estimate&quot;</span>)),</span>
<span id="cb77-18"><a href="inverse-probability-of-treatment-weighting.html#cb77-18" tabindex="-1"></a>  <span class="at">lower     =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="fu">pick</span>(std, <span class="st">&quot;rd&quot;</span>, <span class="st">&quot;conf_low&quot;</span>),</span>
<span id="cb77-19"><a href="inverse-probability-of-treatment-weighting.html#cb77-19" tabindex="-1"></a>                      <span class="fu">pick</span>(ipw, <span class="st">&quot;cox2_init&quot;</span>, <span class="st">&quot;conf.low&quot;</span>)),</span>
<span id="cb77-20"><a href="inverse-probability-of-treatment-weighting.html#cb77-20" tabindex="-1"></a>  <span class="at">upper     =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="fu">pick</span>(std, <span class="st">&quot;rd&quot;</span>, <span class="st">&quot;conf_high&quot;</span>),</span>
<span id="cb77-21"><a href="inverse-probability-of-treatment-weighting.html#cb77-21" tabindex="-1"></a>                      <span class="fu">pick</span>(ipw, <span class="st">&quot;cox2_init&quot;</span>, <span class="st">&quot;conf.high&quot;</span>))</span>
<span id="cb77-22"><a href="inverse-probability-of-treatment-weighting.html#cb77-22" tabindex="-1"></a>)</span>
<span id="cb77-23"><a href="inverse-probability-of-treatment-weighting.html#cb77-23" tabindex="-1"></a></span>
<span id="cb77-24"><a href="inverse-probability-of-treatment-weighting.html#cb77-24" tabindex="-1"></a>comparison <span class="sc">|&gt;</span> knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">estimator</th>
<th align="left">estimand</th>
<th align="right">rd_pp</th>
<th align="right">lower</th>
<th align="right">upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Crude</td>
<td align="left">none (confounded)</td>
<td align="right">2.73</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">Standardization (Ch. 7)</td>
<td align="left">ATE</td>
<td align="right">-0.55</td>
<td align="right">-3.79</td>
<td align="right">2.50</td>
</tr>
<tr class="odd">
<td align="left">IPTW, stabilized</td>
<td align="left">ATE</td>
<td align="right">-0.29</td>
<td align="right">-4.21</td>
<td align="right">3.64</td>
</tr>
</tbody>
</table>
<p>The crude risk difference of
+2.7 percentage points is the confounded
starting point, and both adjusted estimators pull it across the null:
standardization to -0.55 points and IPTW to
-0.29. The agreement is expected rather than
coincidental. Both target the ATE, both use the same nineteen covariates,
and both rest on the same identification assumptions; they differ only in
which nuisance model carries the load —
an outcome model for <code>pud</code> in Chapter 7, a treatment model for
<code>cox2_init</code> here. That two estimators relying on different nuisance
models land in the same place is mild evidence that neither model is
badly wrong, although it is not evidence that the assumptions hold, since
both would be wrong together if <code>ns_covs</code> were missing an important
confounder.</p>
<p>Chapter 8’s matched analysis, recomputed here, gave a risk difference of
-4.2 percentage points, further from the
null than either of these, which is not a contradiction, since
matching targeted the ATT, as the SMR weights above did, averaging over
the older and sicker Cox-2 initiators rather than over the whole cohort,
and did so using roughly a sixth of the data. Its confidence interval
overlaps these comfortably.</p>
<p>All three estimators agree on the shape of the answer. The crude signal
of harm is confounding, and once the arms are made comparable the
estimates hover near the null, with intervals wide enough to admit either
a modest benefit or a modest harm. With 288 ulcer cases and
240 Cox-2 initiators, that is as far as these data can
take us, and no alternative estimator would sharpen the conclusion, since
a better estimator cannot supply information the cohort does not contain.</p>
</div>
<div id="exercises-7" class="section level2 hasAnchor" number="9.8">
<h2><span class="header-section-number">9.8</span> Exercises<a href="inverse-probability-of-treatment-weighting.html#exercises-7" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li>Rerun <code>iptw_estimator()</code> with <code>stabilize = FALSE</code> and compare the
point estimate, the standard error, and the weight distribution to the
stabilized version. The estimate and its robust standard error will be
unchanged; explain why stabilization cannot matter for a <em>saturated</em>
marginal structural model, and describe a setting — an MSM with
effect modifiers, or the time-varying weights of Chapter 11 — where
it would.</li>
<li>Drop five covariates from <code>ns_covs</code> to misspecify the treatment model
— take <code>arthritis</code>, <code>corticosteroid_use</code>, <code>aspirin_use</code>, <code>ppi_use</code>,
and <code>h2_antagonist_use</code>, all plausible confounders — and rerun the
estimator. Report the maximum stabilized weight and the risk
difference under both covariate sets. Which moves more, the estimate
or the weight distribution, and what does that tell you about using
weight diagnostics to detect an inadequate adjustment set?</li>
<li>Formalize what the SMR section did by hand: write <code>iptw_att()</code>, a
copy of <code>iptw_estimator()</code> in which treated patients receive weight 1
and untreated patients receive <code>ps / (1 - ps)</code>. Confirm that it
reproduces the SMR-weighted estimate above, then compare it with
Chapter 8’s matched estimate. Why is stabilization unnecessary for
these weights, and which arm’s weights now carry the long tail?</li>
</ol>

</div>
</div>



            </section>

          </div>
        </div>
      </div>
<a href="propensity-scores.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="survival-outcomes-and-censoring.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": null,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
