<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 14 Sensitivity analysis | Causal Inference in Epidemiology Using R</title>
  <meta name="description" content="An introduction to causal inference with epidemiologic applications in R." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 14 Sensitivity analysis | Causal Inference in Epidemiology Using R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An introduction to causal inference with epidemiologic applications in R." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 14 Sensitivity analysis | Causal Inference in Epidemiology Using R" />
  
  <meta name="twitter:description" content="An introduction to causal inference with epidemiologic applications in R." />
  

<meta name="author" content="M. Alan Brookhart" />


<meta name="date" content="2026-08-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="instrumental-variables.html"/>
<link rel="next" href="r-and-rstudio-setup.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Causal Inference in Epidemiology Using R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="0.1" data-path="preface.html"><a href="preface.html#who-this-book-is-for"><i class="fa fa-check"></i><b>0.1</b> Who this book is for</a></li>
<li class="chapter" data-level="0.2" data-path="preface.html"><a href="preface.html#how-the-book-works"><i class="fa fa-check"></i><b>0.2</b> How the book works</a></li>
<li class="chapter" data-level="0.3" data-path="preface.html"><a href="preface.html#software"><i class="fa fa-check"></i><b>0.3</b> Software</a></li>
</ul></li>
<li class="part"><span><b>I Foundations</b></span></li>
<li class="chapter" data-level="1" data-path="why.html"><a href="why.html"><i class="fa fa-check"></i><b>1</b> Why causal inference?</a>
<ul>
<li class="chapter" data-level="1.1" data-path="why.html"><a href="why.html#questions-epidemiology-cannot-answer-with-association-alone"><i class="fa fa-check"></i><b>1.1</b> Questions epidemiology cannot answer with association alone</a></li>
<li class="chapter" data-level="1.2" data-path="why.html"><a href="why.html#a-first-look-at-the-data"><i class="fa fa-check"></i><b>1.2</b> A first look at the data</a></li>
<li class="chapter" data-level="1.3" data-path="why.html"><a href="why.html#what-this-book-covers"><i class="fa fa-check"></i><b>1.3</b> What this book covers</a></li>
<li class="chapter" data-level="1.4" data-path="why.html"><a href="why.html#how-to-read-this-book"><i class="fa fa-check"></i><b>1.4</b> How to read this book</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-started-with-r-and-the-namcs-data.html"><a href="getting-started-with-r-and-the-namcs-data.html"><i class="fa fa-check"></i><b>2</b> Getting started with R and the NAMCS data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="getting-started-with-r-and-the-namcs-data.html"><a href="getting-started-with-r-and-the-namcs-data.html#r-rstudio-and-the-tidyverse"><i class="fa fa-check"></i><b>2.1</b> R, RStudio, and the tidyverse</a></li>
<li class="chapter" data-level="2.2" data-path="getting-started-with-r-and-the-namcs-data.html"><a href="getting-started-with-r-and-the-namcs-data.html#the-namcs-teaching-cohorts"><i class="fa fa-check"></i><b>2.2</b> The NAMCS teaching cohorts</a></li>
<li class="chapter" data-level="2.3" data-path="getting-started-with-r-and-the-namcs-data.html"><a href="getting-started-with-r-and-the-namcs-data.html#plotting-with-ggplot2"><i class="fa fa-check"></i><b>2.3</b> Plotting with ggplot2</a></li>
<li class="chapter" data-level="2.4" data-path="getting-started-with-r-and-the-namcs-data.html"><a href="getting-started-with-r-and-the-namcs-data.html#your-first-reusable-functions-table-1"><i class="fa fa-check"></i><b>2.4</b> Your first reusable functions: Table 1</a></li>
<li class="chapter" data-level="2.5" data-path="getting-started-with-r-and-the-namcs-data.html"><a href="getting-started-with-r-and-the-namcs-data.html#exercises"><i class="fa fa-check"></i><b>2.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="potential-outcomes-and-causal-effects.html"><a href="potential-outcomes-and-causal-effects.html"><i class="fa fa-check"></i><b>3</b> Potential outcomes and causal effects</a>
<ul>
<li class="chapter" data-level="3.1" data-path="potential-outcomes-and-causal-effects.html"><a href="potential-outcomes-and-causal-effects.html#two-futures-for-every-patient"><i class="fa fa-check"></i><b>3.1</b> Two futures for every patient</a></li>
<li class="chapter" data-level="3.2" data-path="potential-outcomes-and-causal-effects.html"><a href="potential-outcomes-and-causal-effects.html#simulating-both-potential-outcomes"><i class="fa fa-check"></i><b>3.2</b> Simulating both potential outcomes</a></li>
<li class="chapter" data-level="3.3" data-path="potential-outcomes-and-causal-effects.html"><a href="potential-outcomes-and-causal-effects.html#average-causal-effects-and-estimands"><i class="fa fa-check"></i><b>3.3</b> Average causal effects and estimands</a></li>
<li class="chapter" data-level="3.4" data-path="potential-outcomes-and-causal-effects.html"><a href="potential-outcomes-and-causal-effects.html#the-identification-conditions"><i class="fa fa-check"></i><b>3.4</b> The identification conditions</a></li>
<li class="chapter" data-level="3.5" data-path="potential-outcomes-and-causal-effects.html"><a href="potential-outcomes-and-causal-effects.html#exercises-1"><i class="fa fa-check"></i><b>3.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="the-randomized-trial-as-the-benchmark.html"><a href="the-randomized-trial-as-the-benchmark.html"><i class="fa fa-check"></i><b>4</b> The randomized trial as the benchmark</a>
<ul>
<li class="chapter" data-level="4.1" data-path="the-randomized-trial-as-the-benchmark.html"><a href="the-randomized-trial-as-the-benchmark.html#why-randomization-works"><i class="fa fa-check"></i><b>4.1</b> Why randomization works</a></li>
<li class="chapter" data-level="4.2" data-path="the-randomized-trial-as-the-benchmark.html"><a href="the-randomized-trial-as-the-benchmark.html#intention-to-treat-and-per-protocol"><i class="fa fa-check"></i><b>4.2</b> Intention-to-treat and per-protocol</a></li>
<li class="chapter" data-level="4.3" data-path="the-randomized-trial-as-the-benchmark.html"><a href="the-randomized-trial-as-the-benchmark.html#the-target-trial"><i class="fa fa-check"></i><b>4.3</b> The target trial</a></li>
<li class="chapter" data-level="4.4" data-path="the-randomized-trial-as-the-benchmark.html"><a href="the-randomized-trial-as-the-benchmark.html#exercises-2"><i class="fa fa-check"></i><b>4.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="causal-diagrams.html"><a href="causal-diagrams.html"><i class="fa fa-check"></i><b>5</b> Causal diagrams</a>
<ul>
<li class="chapter" data-level="5.1" data-path="causal-diagrams.html"><a href="causal-diagrams.html#drawing-causal-assumptions"><i class="fa fa-check"></i><b>5.1</b> Drawing causal assumptions</a></li>
<li class="chapter" data-level="5.2" data-path="causal-diagrams.html"><a href="causal-diagrams.html#the-nsaidpud-diagram"><i class="fa fa-check"></i><b>5.2</b> The NSAID–PUD diagram</a></li>
<li class="chapter" data-level="5.3" data-path="causal-diagrams.html"><a href="causal-diagrams.html#confounders-colliders-and-mediators"><i class="fa fa-check"></i><b>5.3</b> Confounders, colliders, and mediators</a></li>
<li class="chapter" data-level="5.4" data-path="causal-diagrams.html"><a href="causal-diagrams.html#selection-bias-as-collider-stratification"><i class="fa fa-check"></i><b>5.4</b> Selection bias as collider stratification</a></li>
<li class="chapter" data-level="5.5" data-path="causal-diagrams.html"><a href="causal-diagrams.html#exercises-3"><i class="fa fa-check"></i><b>5.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="study-design-for-causal-questions.html"><a href="study-design-for-causal-questions.html"><i class="fa fa-check"></i><b>6</b> Study design for causal questions</a>
<ul>
<li class="chapter" data-level="6.1" data-path="study-design-for-causal-questions.html"><a href="study-design-for-causal-questions.html#design-before-analysis"><i class="fa fa-check"></i><b>6.1</b> Design before analysis</a></li>
<li class="chapter" data-level="6.2" data-path="study-design-for-causal-questions.html"><a href="study-design-for-causal-questions.html#new-user-designs"><i class="fa fa-check"></i><b>6.2</b> New-user designs</a></li>
<li class="chapter" data-level="6.3" data-path="study-design-for-causal-questions.html"><a href="study-design-for-causal-questions.html#active-comparator-designs"><i class="fa fa-check"></i><b>6.3</b> Active-comparator designs</a></li>
<li class="chapter" data-level="6.4" data-path="study-design-for-causal-questions.html"><a href="study-design-for-causal-questions.html#immortal-time-and-other-time-zero-problems"><i class="fa fa-check"></i><b>6.4</b> Immortal time and other time-zero problems</a></li>
<li class="chapter" data-level="6.5" data-path="study-design-for-causal-questions.html"><a href="study-design-for-causal-questions.html#exercises-4"><i class="fa fa-check"></i><b>6.5</b> Exercises</a></li>
</ul></li>
<li class="part"><span><b>II Core Methods</b></span></li>
<li class="chapter" data-level="7" data-path="outcome-regression-and-standardization.html"><a href="outcome-regression-and-standardization.html"><i class="fa fa-check"></i><b>7</b> Outcome regression and standardization</a>
<ul>
<li class="chapter" data-level="7.1" data-path="outcome-regression-and-standardization.html"><a href="outcome-regression-and-standardization.html#adjusting-with-regression"><i class="fa fa-check"></i><b>7.1</b> Adjusting with regression</a></li>
<li class="chapter" data-level="7.2" data-path="outcome-regression-and-standardization.html"><a href="outcome-regression-and-standardization.html#standardization-predict-then-average"><i class="fa fa-check"></i><b>7.2</b> Standardization: predict, then average</a></li>
<li class="chapter" data-level="7.3" data-path="outcome-regression-and-standardization.html"><a href="outcome-regression-and-standardization.html#the-bootstrap"><i class="fa fa-check"></i><b>7.3</b> The bootstrap</a></li>
<li class="chapter" data-level="7.4" data-path="outcome-regression-and-standardization.html"><a href="outcome-regression-and-standardization.html#effect-modification"><i class="fa fa-check"></i><b>7.4</b> Effect modification</a></li>
<li class="chapter" data-level="7.5" data-path="outcome-regression-and-standardization.html"><a href="outcome-regression-and-standardization.html#exercises-5"><i class="fa fa-check"></i><b>7.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="propensity-scores.html"><a href="propensity-scores.html"><i class="fa fa-check"></i><b>8</b> Propensity scores</a>
<ul>
<li class="chapter" data-level="8.1" data-path="propensity-scores.html"><a href="propensity-scores.html#one-number-that-summarizes-confounding"><i class="fa fa-check"></i><b>8.1</b> One number that summarizes confounding</a></li>
<li class="chapter" data-level="8.2" data-path="propensity-scores.html"><a href="propensity-scores.html#estimating-the-score"><i class="fa fa-check"></i><b>8.2</b> Estimating the score</a></li>
<li class="chapter" data-level="8.3" data-path="propensity-scores.html"><a href="propensity-scores.html#stratification"><i class="fa fa-check"></i><b>8.3</b> Stratification</a></li>
<li class="chapter" data-level="8.4" data-path="propensity-scores.html"><a href="propensity-scores.html#matching"><i class="fa fa-check"></i><b>8.4</b> Matching</a></li>
<li class="chapter" data-level="8.5" data-path="propensity-scores.html"><a href="propensity-scores.html#choosing-the-ps-model"><i class="fa fa-check"></i><b>8.5</b> Choosing the PS model</a></li>
<li class="chapter" data-level="8.6" data-path="propensity-scores.html"><a href="propensity-scores.html#exercises-6"><i class="fa fa-check"></i><b>8.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html"><i class="fa fa-check"></i><b>9</b> Inverse probability of treatment weighting</a>
<ul>
<li class="chapter" data-level="9.1" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#reweighting-to-a-pseudo-population"><i class="fa fa-check"></i><b>9.1</b> Reweighting to a pseudo-population</a></li>
<li class="chapter" data-level="9.2" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#building-the-weights"><i class="fa fa-check"></i><b>9.2</b> Building the weights</a></li>
<li class="chapter" data-level="9.3" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#estimating-the-effect"><i class="fa fa-check"></i><b>9.3</b> Estimating the effect</a></li>
<li class="chapter" data-level="9.4" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#truncation-and-diagnostics"><i class="fa fa-check"></i><b>9.4</b> Truncation and diagnostics</a></li>
<li class="chapter" data-level="9.5" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#standardized-mortality-ratio-weights"><i class="fa fa-check"></i><b>9.5</b> Standardized mortality ratio weights</a></li>
<li class="chapter" data-level="9.6" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#msms-and-where-weighting-shines"><i class="fa fa-check"></i><b>9.6</b> MSMs and where weighting shines</a></li>
<li class="chapter" data-level="9.7" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#three-estimators-one-estimand"><i class="fa fa-check"></i><b>9.7</b> Three estimators, one estimand</a></li>
<li class="chapter" data-level="9.8" data-path="inverse-probability-of-treatment-weighting.html"><a href="inverse-probability-of-treatment-weighting.html#exercises-7"><i class="fa fa-check"></i><b>9.8</b> Exercises</a></li>
</ul></li>
<li class="part"><span><b>III Time, Censoring, and Survival</b></span></li>
<li class="chapter" data-level="10" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html"><i class="fa fa-check"></i><b>10</b> Survival outcomes and censoring</a>
<ul>
<li class="chapter" data-level="10.1" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html#the-statin-question"><i class="fa fa-check"></i><b>10.1</b> The statin question</a></li>
<li class="chapter" data-level="10.2" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html#anatomy-of-time-to-event-data"><i class="fa fa-check"></i><b>10.2</b> Anatomy of time-to-event data</a></li>
<li class="chapter" data-level="10.3" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html#kaplanmeier"><i class="fa fa-check"></i><b>10.3</b> Kaplan–Meier</a></li>
<li class="chapter" data-level="10.4" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html#death-as-a-competing-risk"><i class="fa fa-check"></i><b>10.4</b> Death as a competing risk</a></li>
<li class="chapter" data-level="10.5" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html#risks-versus-hazards"><i class="fa fa-check"></i><b>10.5</b> Risks versus hazards</a></li>
<li class="chapter" data-level="10.6" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html#when-censoring-lies"><i class="fa fa-check"></i><b>10.6</b> When censoring lies</a></li>
<li class="chapter" data-level="10.7" data-path="survival-outcomes-and-censoring.html"><a href="survival-outcomes-and-censoring.html#exercises-8"><i class="fa fa-check"></i><b>10.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="inverse-probability-of-censoring-weights.html"><a href="inverse-probability-of-censoring-weights.html"><i class="fa fa-check"></i><b>11</b> Inverse probability of censoring weights</a>
<ul>
<li class="chapter" data-level="11.1" data-path="inverse-probability-of-censoring-weights.html"><a href="inverse-probability-of-censoring-weights.html#weighting-returns"><i class="fa fa-check"></i><b>11.1</b> Weighting returns</a></li>
<li class="chapter" data-level="11.2" data-path="inverse-probability-of-censoring-weights.html"><a href="inverse-probability-of-censoring-weights.html#person-period-data"><i class="fa fa-check"></i><b>11.2</b> Person-period data</a></li>
<li class="chapter" data-level="11.3" data-path="inverse-probability-of-censoring-weights.html"><a href="inverse-probability-of-censoring-weights.html#building-censoring-weights"><i class="fa fa-check"></i><b>11.3</b> Building censoring weights</a></li>
<li class="chapter" data-level="11.4" data-path="inverse-probability-of-censoring-weights.html"><a href="inverse-probability-of-censoring-weights.html#weight-diagnostics"><i class="fa fa-check"></i><b>11.4</b> Weight diagnostics</a></li>
<li class="chapter" data-level="11.5" data-path="inverse-probability-of-censoring-weights.html"><a href="inverse-probability-of-censoring-weights.html#did-it-matter"><i class="fa fa-check"></i><b>11.5</b> Did it matter?</a></li>
<li class="chapter" data-level="11.6" data-path="inverse-probability-of-censoring-weights.html"><a href="inverse-probability-of-censoring-weights.html#exercises-9"><i class="fa fa-check"></i><b>11.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="clone-censor-weight.html"><a href="clone-censor-weight.html"><i class="fa fa-check"></i><b>12</b> Clone-censor-weight</a>
<ul>
<li class="chapter" data-level="12.1" data-path="clone-censor-weight.html"><a href="clone-censor-weight.html#from-point-treatments-to-treatment-strategies"><i class="fa fa-check"></i><b>12.1</b> From point treatments to treatment strategies</a></li>
<li class="chapter" data-level="12.2" data-path="clone-censor-weight.html"><a href="clone-censor-weight.html#the-clone-censor-weight-recipe"><i class="fa fa-check"></i><b>12.2</b> The clone-censor-weight recipe</a></li>
<li class="chapter" data-level="12.3" data-path="clone-censor-weight.html"><a href="clone-censor-weight.html#deviation-in-the-statin-cohort"><i class="fa fa-check"></i><b>12.3</b> Deviation in the statin cohort</a></li>
<li class="chapter" data-level="12.4" data-path="clone-censor-weight.html"><a href="clone-censor-weight.html#estimating-per-protocol-risk-curves"><i class="fa fa-check"></i><b>12.4</b> Estimating per-protocol risk curves</a></li>
<li class="chapter" data-level="12.5" data-path="clone-censor-weight.html"><a href="clone-censor-weight.html#interpreting-the-per-protocol-effect"><i class="fa fa-check"></i><b>12.5</b> Interpreting the per-protocol effect</a></li>
<li class="chapter" data-level="12.6" data-path="clone-censor-weight.html"><a href="clone-censor-weight.html#exercises-10"><i class="fa fa-check"></i><b>12.6</b> Exercises</a></li>
</ul></li>
<li class="part"><span><b>IV Beyond Exchangeability</b></span></li>
<li class="chapter" data-level="13" data-path="instrumental-variables.html"><a href="instrumental-variables.html"><i class="fa fa-check"></i><b>13</b> Instrumental variables</a>
<ul>
<li class="chapter" data-level="13.1" data-path="instrumental-variables.html"><a href="instrumental-variables.html#when-exchangeability-fails"><i class="fa fa-check"></i><b>13.1</b> When exchangeability fails</a></li>
<li class="chapter" data-level="13.2" data-path="instrumental-variables.html"><a href="instrumental-variables.html#provider-preference-as-an-instrument"><i class="fa fa-check"></i><b>13.2</b> Provider preference as an instrument</a></li>
<li class="chapter" data-level="13.3" data-path="instrumental-variables.html"><a href="instrumental-variables.html#the-wald-and-two-stage-estimators"><i class="fa fa-check"></i><b>13.3</b> The Wald and two-stage estimators</a></li>
<li class="chapter" data-level="13.4" data-path="instrumental-variables.html"><a href="instrumental-variables.html#interpreting-the-late"><i class="fa fa-check"></i><b>13.4</b> Interpreting the LATE</a></li>
<li class="chapter" data-level="13.5" data-path="instrumental-variables.html"><a href="instrumental-variables.html#exercises-11"><i class="fa fa-check"></i><b>13.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="sensitivity-analysis.html"><a href="sensitivity-analysis.html"><i class="fa fa-check"></i><b>14</b> Sensitivity analysis</a>
<ul>
<li class="chapter" data-level="14.1" data-path="sensitivity-analysis.html"><a href="sensitivity-analysis.html#what-we-assumed-and-cannot-check"><i class="fa fa-check"></i><b>14.1</b> What we assumed and cannot check</a></li>
<li class="chapter" data-level="14.2" data-path="sensitivity-analysis.html"><a href="sensitivity-analysis.html#external-adjustment"><i class="fa fa-check"></i><b>14.2</b> External adjustment</a></li>
<li class="chapter" data-level="14.3" data-path="sensitivity-analysis.html"><a href="sensitivity-analysis.html#the-e-value"><i class="fa fa-check"></i><b>14.3</b> The E-value</a></li>
<li class="chapter" data-level="14.4" data-path="sensitivity-analysis.html"><a href="sensitivity-analysis.html#negative-control-outcomes"><i class="fa fa-check"></i><b>14.4</b> Negative control outcomes</a></li>
<li class="chapter" data-level="14.5" data-path="sensitivity-analysis.html"><a href="sensitivity-analysis.html#reporting-a-causal-analysis"><i class="fa fa-check"></i><b>14.5</b> Reporting a causal analysis</a></li>
<li class="chapter" data-level="14.6" data-path="sensitivity-analysis.html"><a href="sensitivity-analysis.html#exercises-12"><i class="fa fa-check"></i><b>14.6</b> Exercises</a></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="r-and-rstudio-setup.html"><a href="r-and-rstudio-setup.html"><i class="fa fa-check"></i><b>A</b> R and RStudio setup</a>
<ul>
<li class="chapter" data-level="A.1" data-path="r-and-rstudio-setup.html"><a href="r-and-rstudio-setup.html#installing-r-and-rstudio"><i class="fa fa-check"></i><b>A.1</b> Installing R and RStudio</a></li>
<li class="chapter" data-level="A.2" data-path="r-and-rstudio-setup.html"><a href="r-and-rstudio-setup.html#installing-the-packages-this-book-uses"><i class="fa fa-check"></i><b>A.2</b> Installing the packages this book uses</a></li>
<li class="chapter" data-level="A.3" data-path="r-and-rstudio-setup.html"><a href="r-and-rstudio-setup.html#installing-the-namcs-teaching-package"><i class="fa fa-check"></i><b>A.3</b> Installing the NAMCS teaching package</a></li>
<li class="chapter" data-level="A.4" data-path="r-and-rstudio-setup.html"><a href="r-and-rstudio-setup.html#loading-everything-a-chapter-needs"><i class="fa fa-check"></i><b>A.4</b> Loading everything a chapter needs</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="namcs-codebook.html"><a href="namcs-codebook.html"><i class="fa fa-check"></i><b>B</b> NAMCS codebook</a>
<ul>
<li class="chapter" data-level="B.1" data-path="namcs-codebook.html"><a href="namcs-codebook.html#the-nsaid-cohort-ns"><i class="fa fa-check"></i><b>B.1</b> The NSAID cohort (<code>ns</code>)</a></li>
<li class="chapter" data-level="B.2" data-path="namcs-codebook.html"><a href="namcs-codebook.html#the-statin-cohort-sta"><i class="fa fa-check"></i><b>B.2</b> The statin cohort (<code>sta</code>)</a></li>
<li class="chapter" data-level="B.3" data-path="namcs-codebook.html"><a href="namcs-codebook.html#a-note-on-the-outcomes"><i class="fa fa-check"></i><b>B.3</b> A note on the outcomes</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="the-estimator-toolkit.html"><a href="the-estimator-toolkit.html"><i class="fa fa-check"></i><b>C</b> The estimator toolkit</a></li>
<li class="chapter" data-level="D" data-path="course-map-phs-921.html"><a href="course-map-phs-921.html"><i class="fa fa-check"></i><b>D</b> Course map: PHS 921</a></li>
<li class="chapter" data-level="E" data-path="further-reading.html"><a href="further-reading.html"><i class="fa fa-check"></i><b>E</b> Further reading</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Causal Inference in Epidemiology Using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="sensitivity-analysis" class="section level1 hasAnchor" number="14">
<h1><span class="header-section-number">Chapter 14</span> Sensitivity analysis<a href="sensitivity-analysis.html#sensitivity-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Chapter 13 went looking for a source of variation in treatment that no
unmeasured confounder could reach, and found one too small to settle
anything. This chapter takes the other road out of the same difficulty.
Instead of replacing the no-unmeasured-confounding assumption, we keep it
and ask what it would cost us to be wrong. How prevalent, and how
prognostic, would a confounder we never recorded have to be before it
accounted for the association we reported? Unlike the assumption itself,
that question has a computable answer. A sensitivity analysis does not
tell us whether an estimate is right, but it does tell us how much
unmeasured confounding would be required to make it wrong, which is a
number a reader can weigh against what she knows about clinical practice.</p>
<div id="what-we-assumed-and-cannot-check" class="section level2 hasAnchor" number="14.1">
<h2><span class="header-section-number">14.1</span> What we assumed and cannot check<a href="sensitivity-analysis.html#what-we-assumed-and-cannot-check" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Every estimate in this book has leaned on conditional exchangeability.
The mechanics varied a great deal: Chapter 7 put the covariates in an
outcome model, Chapters 8 and 9 put them in a treatment model, Chapter 11
added a censoring model and Chapter 12 a deviation model at every
interval. These are four different places to put the same list of
nineteen variables, and one assumption sits underneath all of them: that
within levels of that list, patients who received a Cox-2 selective agent
and patients who received a nonselective NSAID were exchangeable.</p>
<p>Notice the asymmetry between that assumption and its companion.
Positivity leaves traces: Chapter 9’s long tail of large weights and
Chapter 8’s unmatchable patients were the data complaining that some
covariate regions were nearly empty. Exchangeability, in contrast, leaves
nothing behind. A cohort with a severe unmeasured confounder looks exactly
like a cohort with none, with the same balance table, the same overlap
plot, and the same effective sample size. Chapter 8’s diagnostics speak
to the covariates we recorded and, by construction, cannot speak to the
ones we did not.</p>
<p>So there is no test to run, only two useful responses. One is to change
the assumption, which is what Chapter 13 did. The other is to hold it and
quantify the departure that would overturn the finding, and that comes in
two flavors. <strong>External adjustment</strong> asks us to name a specific
confounder and supply its parameters, then returns the corrected
estimate. The <strong>E-value</strong> inverts the question: given the estimate alone,
what is the <em>weakest</em> confounder that would suffice?</p>
</div>
<div id="external-adjustment" class="section level2 hasAnchor" number="14.2">
<h2><span class="header-section-number">14.2</span> External adjustment<a href="sensitivity-analysis.html#external-adjustment" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The term, and the parameterization we use below, are Schneeweiss’s
(2006), written for exactly the healthcare-database setting these
cohorts come from.</p>
<p>Suppose a single binary unmeasured confounder <span class="math inline">\(U\)</span> — present or absent,
measured at baseline, with no interaction with treatment. Three numbers
describe it: its prevalence among the treated, <span class="math inline">\(p_1\)</span>; its prevalence among
the untreated, <span class="math inline">\(p_0\)</span>; and the risk ratio for the outcome comparing
<span class="math inline">\(U = 1\)</span> with <span class="math inline">\(U = 0\)</span>, written <span class="math inline">\(RR_{UD}\)</span> and assumed common to both arms.
The risk ratio we observe is then the true one multiplied by a bias
factor,</p>
<p><span class="math display">\[RR_{\text{obs}} = RR_{\text{true}} \times \frac{p_1 (RR_{UD} - 1) + 1}{p_0 (RR_{UD} - 1) + 1},\]</span></p>
<p>each term of the fraction being the amount by which <span class="math inline">\(U\)</span> inflates the risk
in one arm. Solving for <span class="math inline">\(RR_{\text{true}}\)</span> gives the correction, and the
correction is the whole of our function.</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="sensitivity-analysis.html#cb129-1" tabindex="-1"></a>adjust_rr_unmeasured <span class="ot">&lt;-</span> <span class="cf">function</span>(rr_obs, p_u1, p_u0, rr_ud) {</span>
<span id="cb129-2"><a href="sensitivity-analysis.html#cb129-2" tabindex="-1"></a>  rr_obs <span class="sc">*</span> (p_u0 <span class="sc">*</span> (rr_ud <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span> (p_u1 <span class="sc">*</span> (rr_ud <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb129-3"><a href="sensitivity-analysis.html#cb129-3" tabindex="-1"></a>}</span></code></pre></div>
<p>Two special cases are worth reading off the formula first. If
<span class="math inline">\(p_1 = p_0\)</span> the fraction is 1 however strong <span class="math inline">\(U\)</span> is: a risk factor
distributed identically across arms confounds nothing. If <span class="math inline">\(RR_{UD} = 1\)</span>
the fraction is 1 however unequally <span class="math inline">\(U\)</span> is distributed. This restates
Chapter 5’s requirement, that a confounder needs an arrow into treatment
<em>and</em> an arrow into the outcome, as arithmetic.</p>
<p>Consider a concrete confounder. Cox-2 selective agents were marketed on
gastrointestinal safety, so a clinician worried about a patient’s stomach
had reason to prefer one. Some of that worry is captured in <code>ns_covs</code>,
since <code>ppi_use</code>, <code>h2_antagonist_use</code>, <code>corticosteroid_use</code>, and
<code>aspirin_use</code> are all partial proxies for perceived ulcer risk, and some
of it is not. Over-the-counter NSAID use, meaning the ibuprofen a patient
buys herself on top of what she is prescribed, appears in no survey
field, and heavy alcohol use is asked inconsistently and recorded
incompletely. Both raise ulcer risk, and both plausibly differ between
the arms.</p>
<p>Take a prevalence of 20% among nonselective initiators and sweep the
other two parameters.</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="sensitivity-analysis.html#cb130-1" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;R/propensity.R&quot;</span>); <span class="fu">source</span>(<span class="st">&quot;R/iptw_estimator.R&quot;</span>); <span class="fu">source</span>(<span class="st">&quot;R/sensitivity.R&quot;</span>)</span>
<span id="cb130-2"><a href="sensitivity-analysis.html#cb130-2" tabindex="-1"></a></span>
<span id="cb130-3"><a href="sensitivity-analysis.html#cb130-3" tabindex="-1"></a>ps_model <span class="ot">&lt;-</span> <span class="fu">reformulate</span>(ns_covs, <span class="st">&quot;cox2_init&quot;</span>)</span>
<span id="cb130-4"><a href="sensitivity-analysis.html#cb130-4" tabindex="-1"></a>ipw_rr_fit <span class="ot">&lt;-</span> <span class="fu">iptw_estimator</span>(ns, ps_model, <span class="at">outcome =</span> <span class="st">&quot;pud&quot;</span>, <span class="at">treat =</span> <span class="st">&quot;cox2_init&quot;</span>,</span>
<span id="cb130-5"><a href="sensitivity-analysis.html#cb130-5" tabindex="-1"></a>                             <span class="at">family =</span> <span class="fu">poisson</span>(<span class="at">link =</span> <span class="st">&quot;log&quot;</span>)) <span class="sc">|&gt;</span></span>
<span id="cb130-6"><a href="sensitivity-analysis.html#cb130-6" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">&quot;cox2_init&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb130-7"><a href="sensitivity-analysis.html#cb130-7" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(estimate, conf.low, conf.high), exp))</span>
<span id="cb130-8"><a href="sensitivity-analysis.html#cb130-8" tabindex="-1"></a></span>
<span id="cb130-9"><a href="sensitivity-analysis.html#cb130-9" tabindex="-1"></a>ipw_rr <span class="ot">&lt;-</span> ipw_rr_fit<span class="sc">$</span>estimate</span>
<span id="cb130-10"><a href="sensitivity-analysis.html#cb130-10" tabindex="-1"></a></span>
<span id="cb130-11"><a href="sensitivity-analysis.html#cb130-11" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb130-12"><a href="sensitivity-analysis.html#cb130-12" tabindex="-1"></a>  <span class="at">rr_ud =</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="at">by =</span> <span class="fl">0.05</span>),</span>
<span id="cb130-13"><a href="sensitivity-analysis.html#cb130-13" tabindex="-1"></a>  <span class="at">delta =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.15</span>, <span class="sc">-</span><span class="fl">0.10</span>, <span class="sc">-</span><span class="fl">0.05</span>, <span class="dv">0</span>, <span class="fl">0.05</span>, <span class="fl">0.10</span>, <span class="fl">0.15</span>)</span>
<span id="cb130-14"><a href="sensitivity-analysis.html#cb130-14" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb130-15"><a href="sensitivity-analysis.html#cb130-15" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb130-16"><a href="sensitivity-analysis.html#cb130-16" tabindex="-1"></a>    <span class="at">p_u0 =</span> <span class="fl">0.20</span>,</span>
<span id="cb130-17"><a href="sensitivity-analysis.html#cb130-17" tabindex="-1"></a>    <span class="at">p_u1 =</span> p_u0 <span class="sc">+</span> delta,</span>
<span id="cb130-18"><a href="sensitivity-analysis.html#cb130-18" tabindex="-1"></a>    <span class="at">rr_adj =</span> <span class="fu">adjust_rr_unmeasured</span>(ipw_rr, p_u1, p_u0, rr_ud)</span>
<span id="cb130-19"><a href="sensitivity-analysis.html#cb130-19" tabindex="-1"></a>  )</span></code></pre></div>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="sensitivity-analysis.html#cb131-1" tabindex="-1"></a><span class="fu">ggplot</span>(grid, <span class="fu">aes</span>(rr_ud, rr_adj, <span class="at">colour =</span> <span class="fu">factor</span>(<span class="dv">100</span> <span class="sc">*</span> delta), <span class="at">group =</span> delta)) <span class="sc">+</span></span>
<span id="cb131-2"><a href="sensitivity-analysis.html#cb131-2" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">1</span>, <span class="at">linewidth =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb131-3"><a href="sensitivity-analysis.html#cb131-3" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> ipw_rr, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">colour =</span> <span class="st">&quot;grey50&quot;</span>) <span class="sc">+</span></span>
<span id="cb131-4"><a href="sensitivity-analysis.html#cb131-4" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb131-5"><a href="sensitivity-analysis.html#cb131-5" tabindex="-1"></a>  <span class="fu">scale_colour_viridis_d</span>(<span class="at">end =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb131-6"><a href="sensitivity-analysis.html#cb131-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb131-7"><a href="sensitivity-analysis.html#cb131-7" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">expression</span>(RR[UD]<span class="sc">~</span><span class="st">&quot;: risk ratio for ulcer, confounder present vs absent&quot;</span>),</span>
<span id="cb131-8"><a href="sensitivity-analysis.html#cb131-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Externally adjusted risk ratio&quot;</span>,</span>
<span id="cb131-9"><a href="sensitivity-analysis.html#cb131-9" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">&quot;Prevalence gap</span><span class="sc">\n</span><span class="st">(treated minus</span><span class="sc">\n</span><span class="st">untreated, pp)&quot;</span></span>
<span id="cb131-10"><a href="sensitivity-analysis.html#cb131-10" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb131-11"><a href="sensitivity-analysis.html#cb131-11" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="causal-inference-epi-r_files/figure-html/ch14-extadj-plot-1.png" alt="" width="672" /></p>
<p>The flat line is the case with no imbalance; every curve pivots away from
it, and which way it pivots depends entirely on the sign of the prevalence
gap. Consider the upper family first, where the confounder is more common
among the <em>untreated</em>. If over-the-counter ibuprofen use were rarer among
Cox-2 initiators than among nonselective initiators, part of the apparent
safety of the Cox-2 arm would be that advantage rather than the drug, and
correcting for it raises the risk ratio. A five-point gap is enough to
lift the adjusted estimate to the null once <span class="math inline">\(RR_{UD}\)</span> reaches
1.65; a ten-point gap needs only
1.30, a fifteen-point gap
1.20, and at <span class="math inline">\(RR_{UD} = 3\)</span> that last curve has
carried the estimate to 1.24. None of those
parameter values is extreme. A risk factor that raises ulcer risk by a
fifth and differs by fifteen percentage points between arms is
unremarkable, and yet it is enough to turn our estimate of nothing into
an estimate of harm.</p>
<p>The lower family runs the other way and is the story we would probably
tell first. <strong>Channeling</strong>, meaning the steering of patients with the
worst stomachs toward the drug advertised as gentler on the stomach,
implies exactly the opposite gap, and correcting for it pushes the risk ratio
down: 0.86 at <span class="math inline">\(RR_{UD} = 2\)</span> with a
fifteen-point gap, 0.80 at <span class="math inline">\(RR_{UD} = 3\)</span>. Under
that story our near-null result understates a genuine benefit.</p>
<p>Both families come from the same formula and the same data, and the data
cannot choose between them, which is both the point of the exercise and
the method’s main limitation. It is called <em>external</em> adjustment because
the three parameters must come from outside the analysis, whether from a
validation substudy that measured <span class="math inline">\(U\)</span> on a subsample, a survey, or a
published cohort. When they come from nowhere, the exercise draws a
picture of what-if rather than correcting an estimate, which is worth
doing so long as it is labeled as such. One
further caution: the formula describes a single binary confounder, and
several correlated unmeasured confounders do not collapse into one, so
the arithmetic can understate the joint bias.</p>
</div>
<div id="the-e-value" class="section level2 hasAnchor" number="14.3">
<h2><span class="header-section-number">14.3</span> The E-value<a href="sensitivity-analysis.html#the-e-value" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>External adjustment needed three numbers we do not have, whereas the
<strong>E-value</strong> needs none. It is the minimum strength of association,
expressed as a risk
ratio, that an unmeasured confounder would have to have with <em>both</em> the
treatment and the outcome — conditional on the covariates we did measure —
to explain away the association we observed. The word “both” is doing the
work here, since a variable strongly associated with Cox-2 initiation but
unrelated to ulcers does no damage, and neither does a powerful ulcer risk
factor that is balanced across arms. The E-value is the common value both
associations would have to reach, and no smaller equal pair will do.</p>
<p>The derivation (VanderWeele and Ding 2017) shows that a confounder with
treatment association <span class="math inline">\(a\)</span> and outcome association <span class="math inline">\(b\)</span> can inflate an
observed risk ratio by at most <span class="math inline">\(ab / (a + b - 1)\)</span>. Setting that maximum
equal to the observed risk ratio and imposing <span class="math inline">\(a = b\)</span> gives a closed
form: <span class="math inline">\(E = RR + \sqrt{RR\,(RR - 1)}\)</span>. For a protective estimate we invert
first, since a confounder that could inflate a ratio could equally deflate
its reciprocal.</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="sensitivity-analysis.html#cb132-1" tabindex="-1"></a>evalue_rr <span class="ot">&lt;-</span> <span class="cf">function</span>(rr, <span class="at">conf_low =</span> <span class="cn">NULL</span>, <span class="at">conf_high =</span> <span class="cn">NULL</span>) {</span>
<span id="cb132-2"><a href="sensitivity-analysis.html#cb132-2" tabindex="-1"></a>  ev <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb132-3"><a href="sensitivity-analysis.html#cb132-3" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">is.na</span>(x)) <span class="fu">return</span>(<span class="cn">NA_real_</span>)</span>
<span id="cb132-4"><a href="sensitivity-analysis.html#cb132-4" tabindex="-1"></a>    <span class="cf">if</span> (x <span class="sc">&lt;</span> <span class="dv">1</span>) x <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> x</span>
<span id="cb132-5"><a href="sensitivity-analysis.html#cb132-5" tabindex="-1"></a>    x <span class="sc">+</span> <span class="fu">sqrt</span>(x <span class="sc">*</span> (x <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb132-6"><a href="sensitivity-analysis.html#cb132-6" tabindex="-1"></a>  }</span>
<span id="cb132-7"><a href="sensitivity-analysis.html#cb132-7" tabindex="-1"></a>  ci_bound <span class="ot">&lt;-</span> <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(conf_low) <span class="sc">&amp;&amp;</span> <span class="sc">!</span><span class="fu">is.null</span>(conf_high)) {</span>
<span id="cb132-8"><a href="sensitivity-analysis.html#cb132-8" tabindex="-1"></a>    <span class="co"># E-value for the bound closest to the null</span></span>
<span id="cb132-9"><a href="sensitivity-analysis.html#cb132-9" tabindex="-1"></a>    <span class="cf">if</span> (conf_low <span class="sc">&gt;</span> <span class="dv">1</span>) conf_low <span class="cf">else</span> <span class="cf">if</span> (conf_high <span class="sc">&lt;</span> <span class="dv">1</span>) conf_high <span class="cf">else</span> <span class="dv">1</span></span>
<span id="cb132-10"><a href="sensitivity-analysis.html#cb132-10" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cn">NA_real_</span></span>
<span id="cb132-11"><a href="sensitivity-analysis.html#cb132-11" tabindex="-1"></a>  <span class="fu">tibble</span>(</span>
<span id="cb132-12"><a href="sensitivity-analysis.html#cb132-12" tabindex="-1"></a>    <span class="at">quantity =</span> <span class="fu">c</span>(<span class="st">&quot;point estimate&quot;</span>, <span class="st">&quot;confidence limit&quot;</span>),</span>
<span id="cb132-13"><a href="sensitivity-analysis.html#cb132-13" tabindex="-1"></a>    <span class="at">value    =</span> <span class="fu">c</span>(rr, ci_bound),</span>
<span id="cb132-14"><a href="sensitivity-analysis.html#cb132-14" tabindex="-1"></a>    <span class="at">e_value  =</span> <span class="fu">c</span>(<span class="fu">ev</span>(rr), <span class="cf">if</span> (<span class="fu">is.na</span>(ci_bound)) <span class="cn">NA_real_</span> <span class="cf">else</span> <span class="cf">if</span> (ci_bound <span class="sc">==</span> <span class="dv">1</span>) <span class="dv">1</span> <span class="cf">else</span> <span class="fu">ev</span>(ci_bound))</span>
<span id="cb132-15"><a href="sensitivity-analysis.html#cb132-15" tabindex="-1"></a>  )</span>
<span id="cb132-16"><a href="sensitivity-analysis.html#cb132-16" tabindex="-1"></a>}</span></code></pre></div>
<p>The function returns two rows, and the second matters more. Moving a
<em>point estimate</em> to the null is one question; making a <em>finding</em>
compatible with the null is another, and that requires moving only
whichever confidence bound lies nearer to 1. A result whose interval
already crosses the null needs no help at all, which is why the function
reports a confidence-limit E-value of exactly 1 in that case.</p>
<p>Apply it to Chapter 9’s weighted risk ratio, recomputed above.</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="sensitivity-analysis.html#cb133-1" tabindex="-1"></a>ipw_rr_fit <span class="sc">|&gt;</span></span>
<span id="cb133-2"><a href="sensitivity-analysis.html#cb133-2" tabindex="-1"></a>  <span class="fu">select</span>(estimate, conf.low, conf.high) <span class="sc">|&gt;</span></span>
<span id="cb133-3"><a href="sensitivity-analysis.html#cb133-3" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">estimate</th>
<th align="right">conf.low</th>
<th align="right">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.972</td>
<td align="right">0.654</td>
<td align="right">1.444</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="sensitivity-analysis.html#cb134-1" tabindex="-1"></a><span class="fu">evalue_rr</span>(ipw_rr_fit<span class="sc">$</span>estimate, ipw_rr_fit<span class="sc">$</span>conf.low, ipw_rr_fit<span class="sc">$</span>conf.high) <span class="sc">|&gt;</span></span>
<span id="cb134-2"><a href="sensitivity-analysis.html#cb134-2" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">quantity</th>
<th align="right">value</th>
<th align="right">e_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">point estimate</td>
<td align="right">0.972</td>
<td align="right">1.201</td>
</tr>
<tr class="even">
<td align="left">confidence limit</td>
<td align="right">1.000</td>
<td align="right">1.000</td>
</tr>
</tbody>
</table>
<p>The first row is straightforward. An unmeasured confounder associated with
both Cox-2 initiation and peptic ulcer disease by risk ratios of about
1.20 each, over and above the nineteen covariates,
would suffice to move this estimate to the null, which is a very weak
confounder, weaker than most of the variables we did adjust for. The
second row is blunter still: the interval runs from
0.65 to
1.44 and so already contains 1, so
the E-value is 1 by definition. No unmeasured confounding whatsoever is
required for these data to be compatible with no effect.</p>
<p>It is tempting to read a small E-value as an indictment of the analysis,
although it is better understood as a property of the estimate. Near-null
estimates always
have E-values near 1, because there is almost nothing to explain away, and
the number is doing precisely its job by reporting that this result is
fragile. What would be dishonest is to compute the E-value only when it
comes out large. The same formula applied to the crude risk ratio of
1.28 returns 1.88, and
applied to Chapter 12’s five-year per-protocol risk ratio
(0.28) it returns about
6.6. One formula gives three very different
readings, and much of the difference reflects the size of the estimate
being probed.</p>
<p>That third reading needs a caution the others do not, and it is the
caution that governs how we read any E-value. The quantity is always
defined <em>over and above the covariates already adjusted for</em>, so it is
only as reassuring as the adjustment underneath it. Chapter 9’s weighted
estimate carried nineteen baseline covariates in its weights, so its
E-value of 1.20 genuinely speaks about what was
left unmeasured. Chapter 12’s contrast carried none: as that chapter said
plainly, it weighted for deviation from protocol and left baseline
confounding alone, so the two arms differ at time zero. Its
6.6 therefore describes the <em>total</em> confounding,
measured and unmeasured together, that would be needed to explain the
result away, and a good deal of that total is measured, sitting unused in
<code>sta_covs</code>. Patients who sustain a statin for five years are healthier at
baseline than patients who never start one, in ways the statin cohort
records. The large number is therefore not evidence of robustness, but
mostly a restatement of how far from the null an unadjusted contrast sits,
and an E-value begins to say something about unmeasured confounding only
once the measured kind has been handled.</p>
<p>Two limits deserve mention. The E-value takes the two associations to be
equal, so that if one is known to be weaker the other must be
correspondingly larger, and a contour plot over the pair is the fuller
display. Furthermore, it says nothing about whether such a confounder
exists. What it does is convert an unanswerable question into a smaller
and arguable one, which is the ambition of a sensitivity analysis and the
reason it belongs in the results rather than in the discussion.</p>
</div>
<div id="negative-control-outcomes" class="section level2 hasAnchor" number="14.4">
<h2><span class="header-section-number">14.4</span> Negative control outcomes<a href="sensitivity-analysis.html#negative-control-outcomes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Both devices so far concede that confounding cannot be detected and ask
instead how much of it would be required. There is a third device, and it
is more ambitious: it tries to detect the confounding. A <strong>negative
control outcome</strong> is an outcome the treatment could not plausibly cause,
chosen because it is subject to the same confounding as the outcome we
actually care about. Since the true effect is null by assumption, any
association that survives adjustment cannot be an effect; it is bias, and
bias of roughly the kind afflicting the real analysis. Lipsitch,
Tchetgen Tchetgen, and Cohen (2010, <em>Epidemiology</em>) set out the logic and
the conditions under which it licenses an inference about the primary
estimate.</p>
<p>The examples that made the method famous are worth carrying around. When
influenza vaccination in the elderly is studied in the weeks <em>before</em>
influenza begins circulating, the vaccinated appear substantially
protected from death in a period when the vaccine cannot plausibly be
working. That demonstration is Jackson and colleagues’ (2006). What the
negative control reveals is that the people who get vaccinated are in
better functional health than the people who do not, in ways claims data
do not record. Similarly, patients adherent to statins have fewer
traffic accidents and fewer fractures than nonadherent patients, which
is the healthy-adherer effect declaring itself on an outcome no
lipid-lowering mechanism can reach; that comparison is Dormuth and
colleagues’ (2009). The course gives this a
session of its own (session 23), and rightly, since the technique is best
used as a gate rather than a footnote: if the negative control is run
first and comes back non-null, the primary estimate should not yet be
believed.</p>
<p>Our cohorts carry no true post-treatment negative outcome, so the most we
can do is illustrate the logic with a <em>pre-treatment</em> one. <code>hyperlipidemia</code>
is recorded in <code>ns</code>, is deliberately absent from <code>ns_covs</code>, and cannot be
caused by a prescribing decision made at the same visit. If the weights
built from the other nineteen covariates leave an association with it, the
weights are not reaching all of the confounding structure.</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="sensitivity-analysis.html#cb135-1" tabindex="-1"></a>nco <span class="ot">&lt;-</span> ns <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">hld =</span> <span class="fu">as.integer</span>(hyperlipidemia <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span>))</span>
<span id="cb135-2"><a href="sensitivity-analysis.html#cb135-2" tabindex="-1"></a></span>
<span id="cb135-3"><a href="sensitivity-analysis.html#cb135-3" tabindex="-1"></a>nco_fit <span class="ot">&lt;-</span> <span class="fu">iptw_estimator</span>(nco, ps_model, <span class="at">outcome =</span> <span class="st">&quot;hld&quot;</span>,</span>
<span id="cb135-4"><a href="sensitivity-analysis.html#cb135-4" tabindex="-1"></a>                          <span class="at">treat =</span> <span class="st">&quot;cox2_init&quot;</span>, <span class="at">family =</span> <span class="fu">gaussian</span>()) <span class="sc">|&gt;</span></span>
<span id="cb135-5"><a href="sensitivity-analysis.html#cb135-5" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">&quot;cox2_init&quot;</span>)</span>
<span id="cb135-6"><a href="sensitivity-analysis.html#cb135-6" tabindex="-1"></a>nco_fit</span></code></pre></div>
<pre><code>## # A tibble: 1 × 7
##   term      estimate std.error statistic p.value conf.low conf.high
##   &lt;chr&gt;        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 cox2_init -0.00114    0.0234   0.00238   0.961  -0.0469    0.0446</code></pre>
<p>Crude, hyperlipidemia is recorded for
16.2% of Cox-2 initiators against
13.0% of nonselective initiators, a gap
of +3.2 percentage
points. Weighted, the difference is
-0.11 points, with an interval from
-4.69 to
+4.46. The check passes: weights
that never saw hyperlipidemia nonetheless remove essentially all of its
imbalance, which is mild evidence that the confounding structure they do
capture is broad enough to carry unmeasured correlates of it along.</p>
<p>That result carries two qualifications. The first is why we had to use an
excluded covariate. Anything appearing in the treatment model is balanced
by the fitting itself; running this check on <code>diabetes</code> would return a
near-zero difference no matter how badly confounded the study was, and so
would tell us nothing. The informative negative control is always one the
adjustment did not see. The second is that a pre-treatment variable is a
weaker instrument than a genuine negative control outcome, which would be
measured <em>after</em> time zero and would therefore also probe whether the
follow-up itself is differential — selection, censoring, and detection
effects that a baseline covariate cannot speak to. A passing check here
should be read as one failure mode ruled out, not as exchangeability
established.</p>
<p>The two devices of this chapter are complements: an E-value says how much
confounding <em>could</em> explain an estimate, whereas a negative control asks
whether confounding is <em>still present</em> after adjustment.</p>
</div>
<div id="reporting-a-causal-analysis" class="section level2 hasAnchor" number="14.5">
<h2><span class="header-section-number">14.5</span> Reporting a causal analysis<a href="sensitivity-analysis.html#reporting-a-causal-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Almost everything in this book assembles into a checklist for reporting
one causal analysis honestly, in six items, each of which has had a
chapter of its own.</p>
<ol style="list-style-type: decimal">
<li><strong>State the target trial first</strong> (Chapters 4 and 6). Eligibility, time zero,
the arms, the outcome, the follow-up window, the estimand — written
down before any code is run. Most of what goes wrong in an
observational study goes wrong here, in the alignment of those pieces,
not in the estimator.</li>
<li><strong>Justify the adjustment set with a DAG</strong> (Chapter 5). The covariate
list should follow from an asserted causal structure rather than from
what happens to be in the file. Draw the variables you <em>cannot</em>
measure too, as a node labeled <span class="math inline">\(U\)</span>; that node is what this chapter has
been about.</li>
<li><strong>Show the design-stage diagnostics before any effect estimate</strong>
(Chapters 8 and 9). Balance on every covariate, propensity score
overlap, the weight distribution, the effective sample size. Print
them whether or not they flatter the analysis, since the unflattering
ones are usually the informative ones.</li>
<li><strong>Report marginal contrasts with intervals, and name the estimand</strong>
(Chapters 3, 7, and 10). ATE, ATT, LATE, or per-protocol — these are
different quantities, and a table that mixes them without saying so is
not comparable to itself. Give an absolute and a relative measure: the
risk difference carries the clinical magnitude, the risk ratio travels
better between populations.</li>
<li><strong>Probe the untestable assumption</strong> (this chapter). An E-value beside
the estimate costs one line; an external adjustment, where parameters
exist, costs a paragraph. Alternative specifications — truncation
levels, covariate sets, horizons — belong here too, declared in
advance rather than chosen afterward.</li>
<li><strong>Disclose limitations specifically.</strong> Not “residual confounding
cannot be excluded,” which is true of every observational study ever
published and therefore says nothing, but <em>which</em> variable, in <em>which</em>
direction, and of roughly <em>what</em> magnitude.</li>
</ol>
<p>Running our own Cox-2 analysis through that list gives the following
report. The crude comparison gave a risk difference of
+2.73 percentage points
and a risk ratio of 1.28, apparent harm.
Standardization moved it across the null to
-0.55 points and IPTW to
-0.29 points, two
estimators leaning on different nuisance models and landing in the same
place. Matching gave -4.18 points but for a
different estimand and on roughly a sixth of the data. The instrumental
variable analysis was too wide to constrain anything. Every one of those
intervals spans the null, and the E-value of 1.20
says the weighted estimate would not survive a confounder we would
struggle to notice. With 288 ulcer cases and
240 Cox-2 initiators, the defensible conclusion is that
the crude signal of harm was confounding, and that these data cannot
distinguish a modest harm from a modest benefit. A paper that reported
the matched estimate as evidence of benefit and omitted the rest would be
easy to write and hard to refute from the abstract, and it would be
wrong.</p>
<p>Over fourteen chapters we assembled a toolkit of standardization,
propensity scores, weights for treatment and censoring and protocol
deviation, cloned trials, and instruments, applied all of it to one
modest question about two drugs, and concluded that we do not know the
answer. The methods were not wasted on that conclusion, since they are
what allow us to say that we do not know <em>and</em> to say why, which is a
different position from the false confidence of the crude comparison we
began with. Causal inference is often taught as a collection of
estimators, because estimators are the part that fits into a chapter. The
more durable habit is to ask, before reaching for any of them, what trial
is being emulated, what would have to be true for the answer to mean what
we want it to mean, and how far from true that could be before we would
change our minds. The functions in <code>R/</code> are there to be reused and
rewritten; the habit is the part that transfers.</p>
</div>
<div id="exercises-12" class="section level2 hasAnchor" number="14.6">
<h2><span class="header-section-number">14.6</span> Exercises<a href="sensitivity-analysis.html#exercises-12" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li>Chapter 12’s clone-censor-weight analysis put the five-year risk at
1.61% under sustained statin use and 5.78% under no statin. Compute
the risk ratio, pass it to <code>evalue_rr()</code>, and interpret the result in
a sentence a clinician would understand. Compare it with the
1.20 we obtained here. That bootstrap interval
was wide: explain why the confidence-limit E-value is the number you
would report. Then say what that E-value is a statement <em>about</em>, given
that Chapter 12’s contrast adjusts for deviation from protocol but not
for baseline covariates, and name the E-value assumption that sits
least comfortably with a chapter whose other threat was <em>time-varying</em>
deviation rather than a baseline confounder.</li>
<li>Using <code>adjust_rr_unmeasured()</code>, find the confounder that would fully
explain the crude Cox-2 association, bringing its risk ratio of
1.28 to 1.0. Fix <span class="math inline">\(p_0 = 0.20\)</span> and solve
numerically for the <span class="math inline">\(p_1\)</span> required at <span class="math inline">\(RR_{UD}\)</span> of 1.5, 2, and 3.
Would any of those combinations be credible for a real
gastrointestinal risk factor? Repeat for the IPTW risk ratio and
explain, in terms of the bias factor, why the answer changes so much.</li>
<li>Apply <code>adjust_rr_unmeasured()</code> to the IPTW risk ratio with
<code>p_u1 = 0.10</code>, <code>p_u0 = 0.25</code>, and <code>rr_ud = 2</code> — a confounder much more
common among the <em>untreated</em>. Report the adjusted risk ratio and state
which way the bias was running. Then argue the substance: name a
gastrointestinal risk factor you would expect to be more common among
nonselective initiators than among Cox-2 initiators, explain why that
pattern is harder to justify than channeling, and say which family of
curves in this chapter’s figure a skeptical reader should therefore
find more credible.</li>
<li>Repeat the negative control check with <code>depression</code> in place of
<code>hyperlipidemia</code> — also present in <code>ns</code>, also absent from <code>ns_covs</code>,
and also not caused by the choice of NSAID at initiation. Report the
weighted difference and its interval. Does this control pass as
cleanly as the first? Then argue the harder half: a negative control
is only as good as the claim that it shares the confounding structure
of the real outcome, so say whether depression plausibly sits on the
same paths to peptic ulcer disease as the confounders in <code>ns_covs</code>,
and what a failing check would and would not license you to conclude
about the Cox-2 estimate.</li>
</ol>

</div>
</div>



            </section>

          </div>
        </div>
      </div>
<a href="instrumental-variables.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="r-and-rstudio-setup.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": null,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
